/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../../clock_gater.sv:21.8" *)
module clock_gater(clk_in, rst_n, scan_en, clk_req, gclk_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "../../clock_gater.sv:50.17-52.20" *)
  wire _20_;
  (* src = "../../clock_gater.sv:50.17-52.20" *)
  wire _21_;
  (* src = "../../clock_gater.sv:50.17-52.20" *)
  wire _22_;
  (* src = "../../clock_gater.sv:50.17-52.20" *)
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  (* src = "../../clock_gater.sv:24.28" *)
  input clk_in;
  wire clk_in;
  (* src = "../../clock_gater.sv:27.28" *)
  input [3:0] clk_req;
  wire [3:0] clk_req;
  (* src = "../../clock_gater.sv:34.19" *)
  reg [3:0] enable_latched;
  (* src = "../../clock_gater.sv:28.28" *)
  output [3:0] gclk_out;
  wire [3:0] gclk_out;
  (* src = "../../clock_gater.sv:43.19" *)
  wire \gen_clock_gates[0].enable_in ;
  (* src = "../../clock_gater.sv:43.19" *)
  wire \gen_clock_gates[1].enable_in ;
  (* src = "../../clock_gater.sv:43.19" *)
  wire \gen_clock_gates[2].enable_in ;
  (* src = "../../clock_gater.sv:43.19" *)
  wire \gen_clock_gates[3].enable_in ;
  (* src = "../../clock_gater.sv:25.28" *)
  input rst_n;
  wire rst_n;
  (* src = "../../clock_gater.sv:26.28" *)
  input scan_en;
  wire scan_en;
  assign _00_ = clk_req[0] | (* src = "../../clock_gater.sv:44.32-44.52" *) scan_en;
  assign _01_ = ! (* src = "../../clock_gater.sv:50.21-50.28" *) clk_in;
  (* src = "../../clock_gater.sv:49.13" *)
  always @*
    if (!clk_in) enable_latched[1] = _03_;
  assign _04_ = clk_in & (* src = "../../clock_gater.sv:57.34-57.60" *) enable_latched[1];
  assign _05_ = clk_req[2] | (* src = "../../clock_gater.sv:44.32-44.52" *) scan_en;
  assign _06_ = ! (* src = "../../clock_gater.sv:50.21-50.28" *) clk_in;
  assign _14_ = ! (* src = "../../clock_gater.sv:50.21-50.28" *) clk_in;
  (* src = "../../clock_gater.sv:49.13" *)
  always @*
    if (!clk_in) enable_latched[2] = _08_;
  assign _09_ = clk_in & (* src = "../../clock_gater.sv:57.34-57.60" *) enable_latched[2];
  assign _10_ = clk_req[3] | (* src = "../../clock_gater.sv:44.32-44.52" *) scan_en;
  assign _11_ = ! (* src = "../../clock_gater.sv:50.21-50.28" *) clk_in;
  (* src = "../../clock_gater.sv:49.13" *)
  always @*
    if (!clk_in) enable_latched[3] = _13_;
  assign _15_ = clk_in & (* src = "../../clock_gater.sv:57.34-57.60" *) enable_latched[3];
  (* src = "../../clock_gater.sv:49.13" *)
  always @*
    if (!clk_in) enable_latched[0] = _17_;
  assign _18_ = clk_in & (* src = "../../clock_gater.sv:57.34-57.60" *) enable_latched[0];
  assign _19_ = clk_req[1] | (* src = "../../clock_gater.sv:44.32-44.52" *) scan_en;
  assign _34_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) enable_latched[3] : _10_;
  assign _25_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) 1'h0 : 1'h1;
  assign _27_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) enable_latched[1] : _19_;
  assign _29_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) 1'hx : _19_;
  assign _31_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) 1'h0 : 1'h1;
  assign _33_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) enable_latched[0] : _00_;
  assign _36_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) 1'hx : _00_;
  assign _38_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) 1'h0 : 1'h1;
  assign _41_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) 1'hx : _10_;
  assign _43_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) 1'h0 : 1'h1;
  assign _45_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) enable_latched[2] : _05_;
  assign _47_ = clk_in ? (* src = "../../clock_gater.sv:51.21-51.52|../../clock_gater.sv:50.17-52.20" *) 1'hx : _05_;
  assign \gen_clock_gates[0].enable_in  = _00_;
  assign gclk_out[0] = _18_;
  assign \gen_clock_gates[1].enable_in  = _19_;
  assign gclk_out[1] = _04_;
  assign \gen_clock_gates[2].enable_in  = _05_;
  assign gclk_out[2] = _09_;
  assign \gen_clock_gates[3].enable_in  = _10_;
  assign gclk_out[3] = _15_;
  assign _40_ = _11_;
  assign _23_ = _34_;
  assign _42_ = _11_;
  assign _13_ = _41_;
  assign _44_ = _11_;
  assign _12_ = _43_;
  assign _46_ = _06_;
  assign _22_ = _45_;
  assign _24_ = _06_;
  assign _08_ = _47_;
  assign _26_ = _06_;
  assign _07_ = _25_;
  assign _28_ = _01_;
  assign _21_ = _27_;
  assign _30_ = _01_;
  assign _03_ = _29_;
  assign _32_ = _01_;
  assign _02_ = _31_;
  assign _35_ = _14_;
  assign _20_ = _33_;
  assign _37_ = _14_;
  assign _17_ = _36_;
  assign _39_ = _14_;
  assign _16_ = _38_;
endmodule
