/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../../clock_gater.sv:21.8" *)
module clock_gater(clk_in, rst_n, scan_en, clk_req, gclk_out);
  (* src = "/app/eda.work/70d78cb5-5c32-4971-85a5-31439db74023.edacmd/eda.work/clock_gater.synth/slang/clock_gater.v:6.8-6.12" *)
  wire _00_;
  (* src = "/app/eda.work/70d78cb5-5c32-4971-85a5-31439db74023.edacmd/eda.work/clock_gater.synth/slang/clock_gater.v:9.8-9.12" *)
  wire _03_;
  (* src = "/app/eda.work/70d78cb5-5c32-4971-85a5-31439db74023.edacmd/eda.work/clock_gater.synth/slang/clock_gater.v:10.8-10.12" *)
  wire _04_;
  (* src = "/app/eda.work/70d78cb5-5c32-4971-85a5-31439db74023.edacmd/eda.work/clock_gater.synth/slang/clock_gater.v:11.8-11.12" *)
  wire _05_;
  (* src = "/app/eda.work/70d78cb5-5c32-4971-85a5-31439db74023.edacmd/eda.work/clock_gater.synth/slang/clock_gater.v:15.8-15.12" *)
  wire _09_;
  (* src = "/app/eda.work/70d78cb5-5c32-4971-85a5-31439db74023.edacmd/eda.work/clock_gater.synth/slang/clock_gater.v:16.8-16.12" *)
  wire _10_;
  (* src = "/app/eda.work/70d78cb5-5c32-4971-85a5-31439db74023.edacmd/eda.work/clock_gater.synth/slang/clock_gater.v:21.8-21.12" *)
  wire _15_;
  (* src = "/app/eda.work/70d78cb5-5c32-4971-85a5-31439db74023.edacmd/eda.work/clock_gater.synth/slang/clock_gater.v:24.8-24.12" *)
  wire _18_;
  (* src = "../../clock_gater.sv:24.28" *)
  input clk_in;
  wire clk_in;
  (* src = "../../clock_gater.sv:27.28" *)
  input [3:0] clk_req;
  wire [3:0] clk_req;
  (* src = "../../clock_gater.sv:34.19" *)
  reg [3:0] enable_latched;
  (* src = "../../clock_gater.sv:28.28" *)
  output [3:0] gclk_out;
  wire [3:0] gclk_out;
  (* src = "../../clock_gater.sv:43.19" *)
  wire \gen_clock_gates[0].enable_in ;
  (* src = "../../clock_gater.sv:43.19" *)
  wire \gen_clock_gates[1].enable_in ;
  (* src = "../../clock_gater.sv:43.19" *)
  wire \gen_clock_gates[2].enable_in ;
  (* src = "../../clock_gater.sv:43.19" *)
  wire \gen_clock_gates[3].enable_in ;
  (* src = "../../clock_gater.sv:25.28" *)
  input rst_n;
  wire rst_n;
  (* src = "../../clock_gater.sv:26.28" *)
  input scan_en;
  wire scan_en;
  assign _00_ = scan_en | clk_req[0];
  assign _04_ = enable_latched[1] & clk_in;
  assign _05_ = clk_req[2] | scan_en;
  assign _09_ = enable_latched[2] & clk_in;
  assign _10_ = clk_req[3] | scan_en;
  assign _15_ = enable_latched[3] & clk_in;
  assign _18_ = enable_latched[0] & clk_in;
  assign _03_ = clk_req[1] | scan_en;
  (* src = "../../clock_gater.sv:49.13" *)
  always @*
    if (!clk_in) enable_latched[0] = _00_;
  (* src = "../../clock_gater.sv:49.13" *)
  always @*
    if (!clk_in) enable_latched[3] = _10_;
  (* src = "../../clock_gater.sv:49.13" *)
  always @*
    if (!clk_in) enable_latched[2] = _05_;
  (* src = "../../clock_gater.sv:49.13" *)
  always @*
    if (!clk_in) enable_latched[1] = _03_;
  assign gclk_out = { _15_, _09_, _04_, _18_ };
  assign \gen_clock_gates[0].enable_in  = _00_;
  assign \gen_clock_gates[1].enable_in  = _03_;
  assign \gen_clock_gates[2].enable_in  = _05_;
  assign \gen_clock_gates[3].enable_in  = _10_;
endmodule
