/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../../idle_predictor.sv:10.8" *)
module idle_predictor(clk, rst_n, idle_count, idle_base_th, recent_activity, alpha, sleep_eligible);
  wire [16:0] _00_;
  wire _01_;
  wire [15:0] _02_;
  wire [16:0] _03_;
  wire [15:0] _04_;
  wire _05_;
  wire [15:0] _06_;
  wire [16:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [16:0] _11_;
  wire _12_;
  wire [15:0] _13_;
  (* src = "../../idle_predictor.sv:79.17-83.20" *)
  wire [15:0] _14_;
  (* src = "../../idle_predictor.sv:79.17-83.20" *)
  wire [15:0] _15_;
  (* src = "../../idle_predictor.sv:79.17-83.20" *)
  wire [15:0] _16_;
  (* src = "../../idle_predictor.sv:79.17-83.20" *)
  wire [15:0] _17_;
  (* src = "../../idle_predictor.sv:68.17-72.20" *)
  wire [15:0] _18_;
  (* src = "../../idle_predictor.sv:68.17-72.20" *)
  wire [15:0] _19_;
  (* src = "../../idle_predictor.sv:68.17-72.20" *)
  wire [15:0] _20_;
  (* src = "../../idle_predictor.sv:68.17-72.20" *)
  wire [15:0] _21_;
  wire [15:0] _22_;
  wire _23_;
  wire [15:0] _24_;
  wire _25_;
  wire [15:0] _26_;
  wire _27_;
  wire [15:0] _28_;
  wire _29_;
  wire [15:0] _30_;
  wire _31_;
  wire [15:0] _32_;
  wire _33_;
  wire [15:0] _34_;
  wire _35_;
  wire [15:0] _36_;
  wire _37_;
  (* src = "../../idle_predictor.sv:34.26" *)
  wire [63:0] adaptive_threshold;
  (* src = "../../idle_predictor.sv:24.33" *)
  input [3:0] alpha;
  wire [3:0] alpha;
  (* src = "../../idle_predictor.sv:15.33" *)
  input clk;
  wire clk;
  (* src = "../../idle_predictor.sv:49.29" *)
  wire [15:0] \g_peripheral[0].adjustment ;
  (* src = "../../idle_predictor.sv:51.29" *)
  wire \g_peripheral[0].overflow ;
  (* src = "../../idle_predictor.sv:50.29" *)
  wire [16:0] \g_peripheral[0].sum_extended ;
  (* src = "../../idle_predictor.sv:49.29" *)
  wire [15:0] \g_peripheral[1].adjustment ;
  (* src = "../../idle_predictor.sv:51.29" *)
  wire \g_peripheral[1].overflow ;
  (* src = "../../idle_predictor.sv:50.29" *)
  wire [16:0] \g_peripheral[1].sum_extended ;
  (* src = "../../idle_predictor.sv:49.29" *)
  wire [15:0] \g_peripheral[2].adjustment ;
  (* src = "../../idle_predictor.sv:51.29" *)
  wire \g_peripheral[2].overflow ;
  (* src = "../../idle_predictor.sv:50.29" *)
  wire [16:0] \g_peripheral[2].sum_extended ;
  (* src = "../../idle_predictor.sv:49.29" *)
  wire [15:0] \g_peripheral[3].adjustment ;
  (* src = "../../idle_predictor.sv:51.29" *)
  wire \g_peripheral[3].overflow ;
  (* src = "../../idle_predictor.sv:50.29" *)
  wire [16:0] \g_peripheral[3].sum_extended ;
  (* src = "../../idle_predictor.sv:20.33" *)
  input [63:0] idle_base_th;
  wire [63:0] idle_base_th;
  (* src = "../../idle_predictor.sv:19.33" *)
  input [63:0] idle_count;
  wire [63:0] idle_count;
  (* src = "../../idle_predictor.sv:21.33" *)
  input [3:0] recent_activity;
  wire [3:0] recent_activity;
  (* src = "../../idle_predictor.sv:16.33" *)
  input rst_n;
  wire rst_n;
  (* src = "../../idle_predictor.sv:27.33" *)
  output [3:0] sleep_eligible;
  reg [3:0] sleep_eligible;
  (* src = "../../idle_predictor.sv:35.26" *)
  wire [3:0] sleep_eligible_comb;
  assign _04_ = idle_base_th[15:0] >> (* src = "../../idle_predictor.sv:69.34-69.58" *) alpha;
  assign _00_ = { 1'h0, idle_base_th[31:16] } + (* src = "../../idle_predictor.sv:75.32-75.76" *) { 1'h0, _19_ };
  assign _01_ = idle_count[31:16] >= (* src = "../../idle_predictor.sv:97.43-97.81" *) adaptive_threshold[31:16];
  assign _02_ = idle_base_th[47:32] >> (* src = "../../idle_predictor.sv:69.34-69.58" *) alpha;
  assign _03_ = { 1'h0, idle_base_th[47:32] } + (* src = "../../idle_predictor.sv:75.32-75.76" *) { 1'h0, _20_ };
  assign _05_ = idle_count[47:32] >= (* src = "../../idle_predictor.sv:97.43-97.81" *) adaptive_threshold[47:32];
  assign _06_ = idle_base_th[63:48] >> (* src = "../../idle_predictor.sv:69.34-69.58" *) alpha;
  assign _07_ = { 1'h0, idle_base_th[63:48] } + (* src = "../../idle_predictor.sv:75.32-75.76" *) { 1'h0, _21_ };
  assign _08_ = idle_count[63:48] >= (* src = "../../idle_predictor.sv:97.43-97.81" *) adaptive_threshold[63:48];
  assign _09_ = ! rst_n;
  assign _11_ = { 1'h0, idle_base_th[15:0] } + (* src = "../../idle_predictor.sv:75.32-75.76" *) { 1'h0, _18_ };
  assign _12_ = idle_count[15:0] >= (* src = "../../idle_predictor.sv:97.43-97.81" *) adaptive_threshold[15:0];
  assign _13_ = idle_base_th[31:16] >> (* src = "../../idle_predictor.sv:69.34-69.58" *) alpha;
  (* src = "../../idle_predictor.sv:109.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sleep_eligible <= 4'h0;
    else sleep_eligible <= sleep_eligible_comb;
  assign _22_ = _23_ ? (* full_case = 32'd1 *) (* src = "../../idle_predictor.sv:69.21-69.59|../../idle_predictor.sv:68.17-72.20" *) _13_ : 16'h0000;
  assign _24_ = _25_ ? (* full_case = 32'd1 *) (* src = "../../idle_predictor.sv:80.21-80.55|../../idle_predictor.sv:79.17-83.20" *) 16'hffff : _03_[15:0];
  assign _26_ = _27_ ? (* full_case = 32'd1 *) (* src = "../../idle_predictor.sv:69.21-69.59|../../idle_predictor.sv:68.17-72.20" *) _02_ : 16'h0000;
  assign _32_ = _33_ ? (* full_case = 32'd1 *) (* src = "../../idle_predictor.sv:80.21-80.55|../../idle_predictor.sv:79.17-83.20" *) 16'hffff : _07_[15:0];
  assign _28_ = _29_ ? (* full_case = 32'd1 *) (* src = "../../idle_predictor.sv:80.21-80.55|../../idle_predictor.sv:79.17-83.20" *) 16'hffff : _11_[15:0];
  assign _30_ = _31_ ? (* full_case = 32'd1 *) (* src = "../../idle_predictor.sv:69.21-69.59|../../idle_predictor.sv:68.17-72.20" *) _04_ : 16'h0000;
  assign _34_ = _35_ ? (* full_case = 32'd1 *) (* src = "../../idle_predictor.sv:69.21-69.59|../../idle_predictor.sv:68.17-72.20" *) _06_ : 16'h0000;
  assign _36_ = _37_ ? (* full_case = 32'd1 *) (* src = "../../idle_predictor.sv:80.21-80.55|../../idle_predictor.sv:79.17-83.20" *) 16'hffff : _00_[15:0];
  assign adaptive_threshold[15:0] = _14_;
  assign \g_peripheral[0].adjustment  = _18_;
  assign \g_peripheral[0].sum_extended  = _11_;
  assign \g_peripheral[0].overflow  = _11_[16];
  assign sleep_eligible_comb[0] = _12_;
  assign adaptive_threshold[31:16] = _15_;
  assign \g_peripheral[1].adjustment  = _19_;
  assign \g_peripheral[1].sum_extended  = _00_;
  assign \g_peripheral[1].overflow  = _00_[16];
  assign sleep_eligible_comb[1] = _01_;
  assign adaptive_threshold[47:32] = _16_;
  assign \g_peripheral[2].adjustment  = _20_;
  assign \g_peripheral[2].sum_extended  = _03_;
  assign \g_peripheral[2].overflow  = _03_[16];
  assign sleep_eligible_comb[2] = _05_;
  assign adaptive_threshold[63:48] = _17_;
  assign \g_peripheral[3].adjustment  = _21_;
  assign \g_peripheral[3].sum_extended  = _07_;
  assign \g_peripheral[3].overflow  = _07_[16];
  assign sleep_eligible_comb[3] = _08_;
  assign _33_ = _07_[16];
  assign _17_ = _32_;
  assign _35_ = recent_activity[3];
  assign _21_ = _34_;
  assign _37_ = _00_[16];
  assign _15_ = _36_;
  assign _23_ = recent_activity[1];
  assign _19_ = _22_;
  assign _25_ = _03_[16];
  assign _16_ = _24_;
  assign _27_ = recent_activity[2];
  assign _20_ = _26_;
  assign _29_ = _11_[16];
  assign _14_ = _28_;
  assign _31_ = recent_activity[0];
  assign _18_ = _30_;
  assign _10_ = rst_n;
endmodule
