/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../../perf_counters.sv:11.8" *)
module perf_counters(clk, rst_n, state, sleep_count, active_cycles, idle_cycles);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire [31:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire [31:0] _008_;
  wire _009_;
  wire _010_;
  wire [31:0] _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire [31:0] _017_;
  wire _018_;
  wire _019_;
  wire [31:0] _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire [31:0] _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire [31:0] _029_;
  wire [31:0] _030_;
  wire _031_;
  wire _032_;
  wire [31:0] _033_;
  wire _034_;
  wire _035_;
  wire [31:0] _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire [31:0] _041_;
  wire _042_;
  wire _043_;
  wire [31:0] _044_;
  (* src = "../../perf_counters.sv:34.9-70.12" *)
  wire [127:0] _045_;
  (* src = "../../perf_counters.sv:48.21-50.24" *)
  wire [31:0] _046_;
  (* src = "../../perf_counters.sv:47.17-51.20" *)
  wire [31:0] _047_;
  (* src = "../../perf_counters.sv:48.21-50.24" *)
  wire [31:0] _048_;
  (* src = "../../perf_counters.sv:47.17-51.20" *)
  wire [31:0] _049_;
  (* src = "../../perf_counters.sv:48.21-50.24" *)
  wire [31:0] _050_;
  (* src = "../../perf_counters.sv:47.17-51.20" *)
  wire [31:0] _051_;
  (* src = "../../perf_counters.sv:48.21-50.24" *)
  wire [31:0] _052_;
  (* src = "../../perf_counters.sv:47.17-51.20" *)
  wire [31:0] _053_;
  (* src = "../../perf_counters.sv:34.9-70.12" *)
  wire [127:0] _054_;
  (* src = "../../perf_counters.sv:54.21-56.24" *)
  wire [31:0] _055_;
  (* src = "../../perf_counters.sv:53.17-57.20" *)
  wire [31:0] _056_;
  (* src = "../../perf_counters.sv:54.21-56.24" *)
  wire [31:0] _057_;
  (* src = "../../perf_counters.sv:53.17-57.20" *)
  wire [31:0] _058_;
  (* src = "../../perf_counters.sv:54.21-56.24" *)
  wire [31:0] _059_;
  (* src = "../../perf_counters.sv:53.17-57.20" *)
  wire [31:0] _060_;
  (* src = "../../perf_counters.sv:54.21-56.24" *)
  wire [31:0] _061_;
  (* src = "../../perf_counters.sv:53.17-57.20" *)
  wire [31:0] _062_;
  (* src = "../../perf_counters.sv:34.9-70.12" *)
  wire [7:0] _063_;
  wire _064_;
  wire [31:0] _065_;
  wire _066_;
  wire [31:0] _067_;
  wire _068_;
  wire [31:0] _069_;
  wire _070_;
  wire [31:0] _071_;
  wire [31:0] _072_;
  wire _073_;
  wire [31:0] _074_;
  wire _075_;
  wire [31:0] _076_;
  wire _077_;
  wire [31:0] _078_;
  wire _079_;
  wire _080_;
  wire [31:0] _081_;
  wire _082_;
  wire [31:0] _083_;
  wire _084_;
  wire [31:0] _085_;
  wire _086_;
  wire [31:0] _087_;
  wire _088_;
  wire [31:0] _089_;
  wire _090_;
  wire [31:0] _091_;
  wire _092_;
  wire [31:0] _093_;
  wire [31:0] _094_;
  wire _095_;
  wire [31:0] _096_;
  wire _097_;
  wire [31:0] _098_;
  wire _099_;
  wire [31:0] _100_;
  wire _101_;
  wire _102_;
  wire [31:0] _103_;
  wire _104_;
  wire [31:0] _105_;
  wire _106_;
  wire [31:0] _107_;
  wire _108_;
  wire [31:0] _109_;
  wire _110_;
  wire [31:0] _111_;
  wire [31:0] _112_;
  wire _113_;
  wire [31:0] _114_;
  wire _115_;
  wire [31:0] _116_;
  wire _117_;
  wire _118_;
  wire [7:0] _119_;
  wire _120_;
  wire [127:0] _121_;
  wire _122_;
  wire [127:0] _123_;
  wire _124_;
  wire [31:0] _125_;
  wire [127:0] _126_;
  wire _127_;
  wire _128_;
  wire [31:0] _129_;
  wire [31:0] _130_;
  wire _131_;
  wire [31:0] _132_;
  wire _133_;
  wire [31:0] _134_;
  wire _135_;
  wire [31:0] _136_;
  wire _137_;
  wire _138_;
  wire [31:0] _139_;
  wire _140_;
  wire [31:0] _141_;
  wire _142_;
  wire [31:0] _143_;
  wire _144_;
  wire [31:0] _145_;
  wire [31:0] _146_;
  wire _147_;
  wire [31:0] _148_;
  wire _149_;
  wire [31:0] _150_;
  wire _151_;
  wire [31:0] _152_;
  wire _153_;
  wire _154_;
  wire [31:0] _155_;
  wire _156_;
  wire [31:0] _157_;
  wire _158_;
  wire [31:0] _159_;
  wire _160_;
  wire [31:0] _161_;
  wire _162_;
  wire [31:0] _163_;
  wire _164_;
  wire [31:0] _165_;
  wire _166_;
  wire [31:0] _167_;
  wire [31:0] _168_;
  wire _169_;
  wire [31:0] _170_;
  wire _171_;
  wire [31:0] _172_;
  wire _173_;
  wire [31:0] _174_;
  wire _175_;
  wire _176_;
  wire [31:0] _177_;
  wire _178_;
  wire [31:0] _179_;
  wire _180_;
  wire [31:0] _181_;
  wire _182_;
  wire [31:0] _183_;
  wire _184_;
  wire [31:0] _185_;
  wire _186_;
  wire [31:0] _187_;
  wire _188_;
  wire [31:0] _189_;
  wire _190_;
  wire [31:0] _191_;
  (* src = "../../perf_counters.sv:34.9-70.12" *)
  wire [127:0] _192_;
  (* src = "../../perf_counters.sv:62.21-64.24" *)
  wire [31:0] _193_;
  (* src = "../../perf_counters.sv:61.17-65.20" *)
  wire [31:0] _194_;
  (* src = "../../perf_counters.sv:62.21-64.24" *)
  wire [31:0] _195_;
  (* src = "../../perf_counters.sv:61.17-65.20" *)
  wire [31:0] _196_;
  (* src = "../../perf_counters.sv:62.21-64.24" *)
  wire [31:0] _197_;
  (* src = "../../perf_counters.sv:61.17-65.20" *)
  wire [31:0] _198_;
  (* src = "../../perf_counters.sv:62.21-64.24" *)
  wire [31:0] _199_;
  (* src = "../../perf_counters.sv:61.17-65.20" *)
  wire [31:0] _200_;
  (* src = "../../perf_counters.sv:20.34" *)
  output [127:0] active_cycles;
  reg [127:0] active_cycles;
  (* src = "../../perf_counters.sv:15.33" *)
  input clk;
  wire clk;
  (* src = "../../perf_counters.sv:21.34" *)
  output [127:0] idle_cycles;
  reg [127:0] idle_cycles;
  (* src = "../../perf_counters.sv:30.24" *)
  reg [7:0] prev_state;
  (* src = "../../perf_counters.sv:16.33" *)
  input rst_n;
  wire rst_n;
  (* src = "../../perf_counters.sv:19.34" *)
  output [127:0] sleep_count;
  reg [127:0] sleep_count;
  (* src = "../../perf_counters.sv:17.33" *)
  input [7:0] state;
  wire [7:0] state;
  assign _006_ = ! (* src = "../../perf_counters.sv:34.13-34.19" *) rst_n;
  assign _000_ = prev_state[1:0] != (* src = "../../perf_counters.sv:61.22-61.44" *) 2'h2;
  assign _001_ = state[1:0] == (* src = "../../perf_counters.sv:61.50-61.67" *) 2'h2;
  assign _002_ = _000_ && (* src = "../../perf_counters.sv:61.21-61.68" *) _001_;
  assign _003_ = sleep_count[31:0] != (* src = "../../perf_counters.sv:62.25-62.45" *) 32'd4294967295;
  assign _004_ = sleep_count[31:0] + (* src = "../../perf_counters.sv:63.43-63.64" *) 32'd1;
  assign _005_ = ! (* src = "../../perf_counters.sv:47.21-47.39" *) state[3:2];
  assign _013_ = ! (* src = "../../perf_counters.sv:47.21-47.39" *) state[1:0];
  assign _007_ = active_cycles[63:32] != (* src = "../../perf_counters.sv:48.25-48.47" *) 32'd4294967295;
  assign _008_ = active_cycles[63:32] + (* src = "../../perf_counters.sv:49.45-49.68" *) 32'd1;
  assign _009_ = state[3:2] == (* src = "../../perf_counters.sv:53.21-53.37" *) 2'h1;
  assign _010_ = idle_cycles[63:32] != (* src = "../../perf_counters.sv:54.25-54.45" *) 32'd4294967295;
  assign _011_ = idle_cycles[63:32] + (* src = "../../perf_counters.sv:55.43-55.64" *) 32'd1;
  assign _012_ = prev_state[3:2] != (* src = "../../perf_counters.sv:61.22-61.44" *) 2'h2;
  assign _021_ = active_cycles[31:0] != (* src = "../../perf_counters.sv:48.25-48.47" *) 32'd4294967295;
  assign _014_ = state[3:2] == (* src = "../../perf_counters.sv:61.50-61.67" *) 2'h2;
  assign _015_ = _012_ && (* src = "../../perf_counters.sv:61.21-61.68" *) _014_;
  assign _016_ = sleep_count[63:32] != (* src = "../../perf_counters.sv:62.25-62.45" *) 32'd4294967295;
  assign _017_ = sleep_count[63:32] + (* src = "../../perf_counters.sv:63.43-63.64" *) 32'd1;
  assign _018_ = ! (* src = "../../perf_counters.sv:47.21-47.39" *) state[5:4];
  assign _019_ = active_cycles[95:64] != (* src = "../../perf_counters.sv:48.25-48.47" *) 32'd4294967295;
  assign _020_ = active_cycles[95:64] + (* src = "../../perf_counters.sv:49.45-49.68" *) 32'd1;
  assign _029_ = active_cycles[31:0] + (* src = "../../perf_counters.sv:49.45-49.68" *) 32'd1;
  assign _022_ = state[5:4] == (* src = "../../perf_counters.sv:53.21-53.37" *) 2'h1;
  assign _023_ = idle_cycles[95:64] != (* src = "../../perf_counters.sv:54.25-54.45" *) 32'd4294967295;
  assign _024_ = idle_cycles[95:64] + (* src = "../../perf_counters.sv:55.43-55.64" *) 32'd1;
  assign _025_ = prev_state[5:4] != (* src = "../../perf_counters.sv:61.22-61.44" *) 2'h2;
  assign _026_ = state[5:4] == (* src = "../../perf_counters.sv:61.50-61.67" *) 2'h2;
  assign _027_ = _025_ && (* src = "../../perf_counters.sv:61.21-61.68" *) _026_;
  assign _028_ = sleep_count[95:64] != (* src = "../../perf_counters.sv:62.25-62.45" *) 32'd4294967295;
  assign _030_ = sleep_count[95:64] + (* src = "../../perf_counters.sv:63.43-63.64" *) 32'd1;
  assign _031_ = ! (* src = "../../perf_counters.sv:47.21-47.39" *) state[7:6];
  assign _032_ = active_cycles[127:96] != (* src = "../../perf_counters.sv:48.25-48.47" *) 32'd4294967295;
  assign _033_ = active_cycles[127:96] + (* src = "../../perf_counters.sv:49.45-49.68" *) 32'd1;
  assign _034_ = state[7:6] == (* src = "../../perf_counters.sv:53.21-53.37" *) 2'h1;
  assign _035_ = idle_cycles[127:96] != (* src = "../../perf_counters.sv:54.25-54.45" *) 32'd4294967295;
  assign _036_ = idle_cycles[127:96] + (* src = "../../perf_counters.sv:55.43-55.64" *) 32'd1;
  assign _037_ = prev_state[7:6] != (* src = "../../perf_counters.sv:61.22-61.44" *) 2'h2;
  assign _038_ = state[7:6] == (* src = "../../perf_counters.sv:61.50-61.67" *) 2'h2;
  assign _039_ = _037_ && (* src = "../../perf_counters.sv:61.21-61.68" *) _038_;
  assign _040_ = sleep_count[127:96] != (* src = "../../perf_counters.sv:62.25-62.45" *) 32'd4294967295;
  assign _041_ = sleep_count[127:96] + (* src = "../../perf_counters.sv:63.43-63.64" *) 32'd1;
  assign _042_ = state[1:0] == (* src = "../../perf_counters.sv:53.21-53.37" *) 2'h1;
  assign _043_ = idle_cycles[31:0] != (* src = "../../perf_counters.sv:54.25-54.45" *) 32'd4294967295;
  assign _044_ = idle_cycles[31:0] + (* src = "../../perf_counters.sv:55.43-55.64" *) 32'd1;
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    active_cycles[31:0] <= _045_[31:0];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    active_cycles[63:32] <= _045_[63:32];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    active_cycles[95:64] <= _045_[95:64];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    active_cycles[127:96] <= _045_[127:96];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    idle_cycles[31:0] <= _054_[31:0];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    idle_cycles[63:32] <= _054_[63:32];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    idle_cycles[95:64] <= _054_[95:64];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    idle_cycles[127:96] <= _054_[127:96];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    prev_state[1:0] <= _063_[1:0];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    prev_state[3:2] <= _063_[3:2];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    prev_state[5:4] <= _063_[5:4];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    prev_state[7:6] <= _063_[7:6];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    sleep_count[31:0] <= _192_[31:0];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    sleep_count[63:32] <= _192_[63:32];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    sleep_count[95:64] <= _192_[95:64];
  (* src = "../../perf_counters.sv:33.5" *)
  always @(posedge clk)
    sleep_count[127:96] <= _192_[127:96];
  assign _129_ = _137_ ? (* src = "../../perf_counters.sv:63.25-63.65|../../perf_counters.sv:62.21-64.24" *) _041_ : sleep_count[127:96];
  assign _071_ = _080_ ? (* src = "../../perf_counters.sv:62.21-64.24|../../perf_counters.sv:61.17-65.20" *) _193_ : sleep_count[127:96];
  assign _065_ = _066_ ? (* src = "../../perf_counters.sv:54.21-56.24|../../perf_counters.sv:53.17-57.20" *) _191_ : 32'hxxxxxxxx;
  assign _067_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _065_ : 32'hxxxxxxxx;
  assign _069_ = _070_ ? (* src = "../../perf_counters.sv:54.21-56.24|../../perf_counters.sv:53.17-57.20" *) _059_ : idle_cycles[63:32];
  assign _072_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _069_ : 32'hxxxxxxxx;
  assign _074_ = _075_ ? (* src = "../../perf_counters.sv:49.25-49.69|../../perf_counters.sv:48.21-50.24" *) _008_ : active_cycles[63:32];
  assign _076_ = _077_ ? (* src = "../../perf_counters.sv:48.21-50.24|../../perf_counters.sv:47.17-51.20" *) _074_ : 32'hxxxxxxxx;
  assign _078_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _076_ : 32'hxxxxxxxx;
  assign _081_ = _082_ ? (* src = "../../perf_counters.sv:48.21-50.24|../../perf_counters.sv:47.17-51.20" *) _050_ : active_cycles[63:32];
  assign _083_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _081_ : 32'hxxxxxxxx;
  assign _085_ = _086_ ? (* src = "../../perf_counters.sv:63.25-63.65|../../perf_counters.sv:62.21-64.24" *) _004_ : sleep_count[31:0];
  assign _087_ = _088_ ? (* src = "../../perf_counters.sv:62.21-64.24|../../perf_counters.sv:61.17-65.20" *) _085_ : 32'hxxxxxxxx;
  assign _094_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _071_ : 32'hxxxxxxxx;
  assign _089_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _087_ : 32'hxxxxxxxx;
  assign _091_ = _092_ ? (* src = "../../perf_counters.sv:62.21-64.24|../../perf_counters.sv:61.17-65.20" *) _195_ : sleep_count[31:0];
  assign _093_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _091_ : 32'hxxxxxxxx;
  assign _096_ = _097_ ? (* src = "../../perf_counters.sv:55.25-55.65|../../perf_counters.sv:54.21-56.24" *) _044_ : idle_cycles[31:0];
  assign _098_ = _099_ ? (* src = "../../perf_counters.sv:54.21-56.24|../../perf_counters.sv:53.17-57.20" *) _096_ : 32'hxxxxxxxx;
  assign _100_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _098_ : 32'hxxxxxxxx;
  assign _111_ = _118_ ? (* src = "../../perf_counters.sv:55.25-55.65|../../perf_counters.sv:54.21-56.24" *) _036_ : idle_cycles[127:96];
  assign _103_ = _104_ ? (* src = "../../perf_counters.sv:54.21-56.24|../../perf_counters.sv:53.17-57.20" *) _057_ : idle_cycles[31:0];
  assign _105_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _103_ : 32'hxxxxxxxx;
  assign _107_ = _108_ ? (* src = "../../perf_counters.sv:49.25-49.69|../../perf_counters.sv:48.21-50.24" *) _029_ : active_cycles[31:0];
  assign _109_ = _110_ ? (* src = "../../perf_counters.sv:48.21-50.24|../../perf_counters.sv:47.17-51.20" *) _107_ : 32'hxxxxxxxx;
  assign _112_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _109_ : 32'hxxxxxxxx;
  assign _114_ = _115_ ? (* src = "../../perf_counters.sv:48.21-50.24|../../perf_counters.sv:47.17-51.20" *) _048_ : active_cycles[31:0];
  assign _116_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _114_ : 32'hxxxxxxxx;
  assign _125_ = _128_ ? (* src = "../../perf_counters.sv:54.21-56.24|../../perf_counters.sv:53.17-57.20" *) _111_ : 32'hxxxxxxxx;
  assign _119_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) state : 8'h00;
  assign _121_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) { _056_, _062_, _060_, _058_ } : 128'h00000000000000000000000000000000;
  assign _123_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) { _047_, _053_, _051_, _049_ } : 128'h00000000000000000000000000000000;
  assign _126_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) { _194_, _200_, _198_, _196_ } : 128'h00000000000000000000000000000000;
  assign _130_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _125_ : 32'hxxxxxxxx;
  assign _132_ = _133_ ? (* src = "../../perf_counters.sv:54.21-56.24|../../perf_counters.sv:53.17-57.20" *) _055_ : idle_cycles[127:96];
  assign _134_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _132_ : 32'hxxxxxxxx;
  assign _136_ = _138_ ? (* src = "../../perf_counters.sv:49.25-49.69|../../perf_counters.sv:48.21-50.24" *) _033_ : active_cycles[127:96];
  assign _145_ = _154_ ? (* src = "../../perf_counters.sv:62.21-64.24|../../perf_counters.sv:61.17-65.20" *) _129_ : 32'hxxxxxxxx;
  assign _139_ = _140_ ? (* src = "../../perf_counters.sv:48.21-50.24|../../perf_counters.sv:47.17-51.20" *) _136_ : 32'hxxxxxxxx;
  assign _141_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _139_ : 32'hxxxxxxxx;
  assign _143_ = _144_ ? (* src = "../../perf_counters.sv:48.21-50.24|../../perf_counters.sv:47.17-51.20" *) _046_ : active_cycles[127:96];
  assign _146_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _143_ : 32'hxxxxxxxx;
  assign _148_ = _149_ ? (* src = "../../perf_counters.sv:63.25-63.65|../../perf_counters.sv:62.21-64.24" *) _030_ : sleep_count[95:64];
  assign _150_ = _151_ ? (* src = "../../perf_counters.sv:62.21-64.24|../../perf_counters.sv:61.17-65.20" *) _148_ : 32'hxxxxxxxx;
  assign _152_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _150_ : 32'hxxxxxxxx;
  assign _155_ = _156_ ? (* src = "../../perf_counters.sv:62.21-64.24|../../perf_counters.sv:61.17-65.20" *) _199_ : sleep_count[95:64];
  assign _157_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _155_ : 32'hxxxxxxxx;
  assign _159_ = _160_ ? (* src = "../../perf_counters.sv:55.25-55.65|../../perf_counters.sv:54.21-56.24" *) _024_ : idle_cycles[95:64];
  assign _161_ = _162_ ? (* src = "../../perf_counters.sv:54.21-56.24|../../perf_counters.sv:53.17-57.20" *) _159_ : 32'hxxxxxxxx;
  assign _168_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _145_ : 32'hxxxxxxxx;
  assign _163_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _161_ : 32'hxxxxxxxx;
  assign _165_ = _166_ ? (* src = "../../perf_counters.sv:54.21-56.24|../../perf_counters.sv:53.17-57.20" *) _061_ : idle_cycles[95:64];
  assign _167_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _165_ : 32'hxxxxxxxx;
  assign _170_ = _171_ ? (* src = "../../perf_counters.sv:49.25-49.69|../../perf_counters.sv:48.21-50.24" *) _020_ : active_cycles[95:64];
  assign _172_ = _173_ ? (* src = "../../perf_counters.sv:48.21-50.24|../../perf_counters.sv:47.17-51.20" *) _170_ : 32'hxxxxxxxx;
  assign _174_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _172_ : 32'hxxxxxxxx;
  assign _177_ = _178_ ? (* src = "../../perf_counters.sv:48.21-50.24|../../perf_counters.sv:47.17-51.20" *) _052_ : active_cycles[95:64];
  assign _179_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _177_ : 32'hxxxxxxxx;
  assign _181_ = _182_ ? (* src = "../../perf_counters.sv:63.25-63.65|../../perf_counters.sv:62.21-64.24" *) _017_ : sleep_count[63:32];
  assign _183_ = _184_ ? (* src = "../../perf_counters.sv:62.21-64.24|../../perf_counters.sv:61.17-65.20" *) _181_ : 32'hxxxxxxxx;
  assign _185_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _183_ : 32'hxxxxxxxx;
  assign _187_ = _188_ ? (* src = "../../perf_counters.sv:62.21-64.24|../../perf_counters.sv:61.17-65.20" *) _197_ : sleep_count[63:32];
  assign _189_ = rst_n ? (* full_case = 32'd1 *) (* src = "../../perf_counters.sv:36.13-41.16|../../perf_counters.sv:34.9-70.12" *) _187_ : 32'hxxxxxxxx;
  assign _191_ = _064_ ? (* src = "../../perf_counters.sv:55.25-55.65|../../perf_counters.sv:54.21-56.24" *) _011_ : idle_cycles[63:32];
  assign _137_ = _040_;
  assign _154_ = _039_;
  assign _176_ = _006_;
  assign _193_ = _168_;
  assign _080_ = _039_;
  assign _102_ = _006_;
  assign _194_ = _094_;
  assign _118_ = _035_;
  assign _128_ = _034_;
  assign _131_ = _006_;
  assign _055_ = _130_;
  assign _133_ = _034_;
  assign _135_ = _006_;
  assign _056_ = _134_;
  assign _138_ = _032_;
  assign _140_ = _031_;
  assign _142_ = _006_;
  assign _046_ = _141_;
  assign _144_ = _031_;
  assign _147_ = _006_;
  assign _047_ = _146_;
  assign _149_ = _028_;
  assign _151_ = _027_;
  assign _153_ = _006_;
  assign _199_ = _152_;
  assign _156_ = _027_;
  assign _158_ = _006_;
  assign _200_ = _157_;
  assign _160_ = _023_;
  assign _162_ = _022_;
  assign _164_ = _006_;
  assign _061_ = _163_;
  assign _166_ = _022_;
  assign _169_ = _006_;
  assign _062_ = _167_;
  assign _171_ = _019_;
  assign _173_ = _018_;
  assign _175_ = _006_;
  assign _052_ = _174_;
  assign _178_ = _018_;
  assign _180_ = _006_;
  assign _053_ = _179_;
  assign _182_ = _016_;
  assign _184_ = _015_;
  assign _186_ = _006_;
  assign _197_ = _185_;
  assign _188_ = _015_;
  assign _190_ = _006_;
  assign _198_ = _189_;
  assign _064_ = _010_;
  assign _066_ = _009_;
  assign _068_ = _006_;
  assign _059_ = _067_;
  assign _070_ = _009_;
  assign _073_ = _006_;
  assign _060_ = _072_;
  assign _075_ = _007_;
  assign _077_ = _005_;
  assign _079_ = _006_;
  assign _050_ = _078_;
  assign _082_ = _005_;
  assign _084_ = _006_;
  assign _051_ = _083_;
  assign _086_ = _003_;
  assign _088_ = _002_;
  assign _090_ = _006_;
  assign _195_ = _089_;
  assign _092_ = _002_;
  assign _095_ = _006_;
  assign _196_ = _093_;
  assign _097_ = _043_;
  assign _099_ = _042_;
  assign _101_ = _006_;
  assign _057_ = _100_;
  assign _104_ = _042_;
  assign _106_ = _006_;
  assign _058_ = _105_;
  assign _108_ = _021_;
  assign _110_ = _013_;
  assign _113_ = _006_;
  assign _048_ = _112_;
  assign _115_ = _013_;
  assign _117_ = _006_;
  assign _049_ = _116_;
  assign _120_ = _006_;
  assign _063_ = _119_;
  assign _122_ = _006_;
  assign _054_ = _121_;
  assign _124_ = _006_;
  assign _045_ = _123_;
  assign _127_ = _006_;
  assign _192_ = _126_;
endmodule
