/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../../activity_counter.sv:8.8" *)
module activity_counter(clk, rst_n, activity_pulse, periph_en, idle_count, recent_activity);
  wire _000_;
  wire [15:0] _001_;
  wire _002_;
  wire _003_;
  wire [15:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire [15:0] _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire [3:0] _014_;
  wire _015_;
  wire _016_;
  wire [3:0] _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire [3:0] _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire [3:0] _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire [15:0] _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  (* src = "../../activity_counter.sv:83.26-90.20" *)
  wire [3:0] _036_;
  (* src = "../../activity_counter.sv:78.26-90.20" *)
  wire [3:0] _037_;
  (* src = "../../activity_counter.sv:74.17-90.20" *)
  wire [3:0] _038_;
  (* src = "../../activity_counter.sv:83.26-90.20" *)
  wire [3:0] _039_;
  (* src = "../../activity_counter.sv:78.26-90.20" *)
  wire [3:0] _040_;
  (* src = "../../activity_counter.sv:74.17-90.20" *)
  wire [3:0] _041_;
  (* src = "../../activity_counter.sv:83.26-90.20" *)
  wire [3:0] _042_;
  (* src = "../../activity_counter.sv:78.26-90.20" *)
  wire [3:0] _043_;
  (* src = "../../activity_counter.sv:74.17-90.20" *)
  wire [3:0] _044_;
  (* src = "../../activity_counter.sv:83.26-90.20" *)
  wire [3:0] _045_;
  (* src = "../../activity_counter.sv:78.26-90.20" *)
  wire [3:0] _046_;
  (* src = "../../activity_counter.sv:74.17-90.20" *)
  wire [3:0] _047_;
  (* src = "../../activity_counter.sv:53.26-60.20" *)
  wire [15:0] _048_;
  (* src = "../../activity_counter.sv:49.26-60.20" *)
  wire [15:0] _049_;
  (* src = "../../activity_counter.sv:45.17-60.20" *)
  wire [15:0] _050_;
  (* src = "../../activity_counter.sv:53.26-60.20" *)
  wire [15:0] _051_;
  (* src = "../../activity_counter.sv:49.26-60.20" *)
  wire [15:0] _052_;
  (* src = "../../activity_counter.sv:45.17-60.20" *)
  wire [15:0] _053_;
  (* src = "../../activity_counter.sv:53.26-60.20" *)
  wire [15:0] _054_;
  (* src = "../../activity_counter.sv:49.26-60.20" *)
  wire [15:0] _055_;
  (* src = "../../activity_counter.sv:45.17-60.20" *)
  wire [15:0] _056_;
  (* src = "../../activity_counter.sv:53.26-60.20" *)
  wire [15:0] _057_;
  (* src = "../../activity_counter.sv:49.26-60.20" *)
  wire [15:0] _058_;
  (* src = "../../activity_counter.sv:45.17-60.20" *)
  wire [15:0] _059_;
  wire _060_;
  wire [15:0] _061_;
  wire _062_;
  wire [15:0] _063_;
  wire _064_;
  wire [15:0] _065_;
  wire _066_;
  wire [15:0] _067_;
  wire _068_;
  wire [15:0] _069_;
  wire _070_;
  wire [15:0] _071_;
  wire _072_;
  wire [15:0] _073_;
  wire _074_;
  wire [15:0] _075_;
  wire _076_;
  wire [15:0] _077_;
  wire _078_;
  wire [3:0] _079_;
  wire [15:0] _080_;
  wire _081_;
  wire [15:0] _082_;
  wire _083_;
  wire [15:0] _084_;
  wire _085_;
  wire _086_;
  wire [15:0] _087_;
  wire _088_;
  wire [15:0] _089_;
  wire _090_;
  wire [15:0] _091_;
  wire _092_;
  wire [15:0] _093_;
  wire _094_;
  wire [15:0] _095_;
  wire _096_;
  wire [15:0] _097_;
  wire [3:0] _098_;
  wire _099_;
  wire _100_;
  wire [3:0] _101_;
  wire _102_;
  wire [3:0] _103_;
  wire _104_;
  wire [3:0] _105_;
  wire _106_;
  wire [3:0] _107_;
  wire _108_;
  wire [3:0] _109_;
  wire [3:0] _110_;
  wire _111_;
  wire [3:0] _112_;
  wire _113_;
  wire [3:0] _114_;
  wire _115_;
  wire _116_;
  wire [3:0] _117_;
  wire _118_;
  wire [3:0] _119_;
  wire _120_;
  wire [3:0] _121_;
  wire _122_;
  wire [3:0] _123_;
  wire _124_;
  wire [3:0] _125_;
  wire _126_;
  wire [3:0] _127_;
  wire [3:0] _128_;
  wire _129_;
  wire [3:0] _130_;
  wire _131_;
  wire [3:0] _132_;
  wire _133_;
  wire [3:0] _134_;
  wire _135_;
  wire _136_;
  wire [3:0] _137_;
  wire _138_;
  wire [3:0] _139_;
  wire _140_;
  wire [3:0] _141_;
  wire _142_;
  wire [15:0] _143_;
  wire _144_;
  wire [15:0] _145_;
  wire _146_;
  wire [15:0] _147_;
  wire _148_;
  wire [3:0] _149_;
  wire [15:0] _150_;
  wire _151_;
  wire [15:0] _152_;
  wire _153_;
  wire [15:0] _154_;
  wire _155_;
  (* src = "../../activity_counter.sv:18.37" *)
  input [3:0] activity_pulse;
  wire [3:0] activity_pulse;
  (* src = "../../activity_counter.sv:32.46" *)
  reg [15:0] activity_timer;
  (* src = "../../activity_counter.sv:14.37" *)
  input clk;
  wire clk;
  (* src = "../../activity_counter.sv:24.37" *)
  output [63:0] idle_count;
  wire [63:0] idle_count;
  (* src = "../../activity_counter.sv:31.29" *)
  reg [63:0] idle_counter;
  (* src = "../../activity_counter.sv:21.37" *)
  input [3:0] periph_en;
  wire [3:0] periph_en;
  (* src = "../../activity_counter.sv:25.37" *)
  output [3:0] recent_activity;
  wire [3:0] recent_activity;
  (* src = "../../activity_counter.sv:15.37" *)
  input rst_n;
  wire rst_n;
  assign _005_ = ! rst_n;
  assign _000_ = idle_counter[31:16] < (* src = "../../activity_counter.sv:53.30-53.57" *) 16'hffff;
  assign _001_ = idle_counter[31:16] + (* src = "../../activity_counter.sv:55.40-55.62" *) 16'h0001;
  assign _002_ = ! (* src = "../../activity_counter.sv:45.21-45.34" *) periph_en[2];
  assign _003_ = idle_counter[47:32] < (* src = "../../activity_counter.sv:53.30-53.57" *) 16'hffff;
  assign _004_ = idle_counter[47:32] + (* src = "../../activity_counter.sv:55.40-55.62" *) 16'h0001;
  assign _006_ = ! (* src = "../../activity_counter.sv:45.21-45.34" *) periph_en[3];
  assign _007_ = idle_counter[63:48] < (* src = "../../activity_counter.sv:53.30-53.57" *) 16'hffff;
  assign _008_ = idle_counter[63:48] + (* src = "../../activity_counter.sv:55.40-55.62" *) 16'h0001;
  assign _009_ = ! rst_n;
  assign _018_ = ! (* src = "../../activity_counter.sv:45.21-45.34" *) periph_en[0];
  assign _012_ = ! (* src = "../../activity_counter.sv:74.21-74.34" *) periph_en[0];
  assign _013_ = { 28'h0000000, activity_timer[3:0] } > (* src = "../../activity_counter.sv:83.30-83.51" *) 32'd0;
  assign _014_ = activity_timer[3:0] - (* src = "../../activity_counter.sv:85.42-85.66" *) 4'h1;
  assign _015_ = ! (* src = "../../activity_counter.sv:74.21-74.34" *) periph_en[1];
  assign _016_ = { 28'h0000000, activity_timer[7:4] } > (* src = "../../activity_counter.sv:83.30-83.51" *) 32'd0;
  assign _017_ = activity_timer[7:4] - (* src = "../../activity_counter.sv:85.42-85.66" *) 4'h1;
  assign _024_ = idle_counter[15:0] < (* src = "../../activity_counter.sv:53.30-53.57" *) 16'hffff;
  assign _019_ = ! (* src = "../../activity_counter.sv:74.21-74.34" *) periph_en[2];
  assign _020_ = { 28'h0000000, activity_timer[11:8] } > (* src = "../../activity_counter.sv:83.30-83.51" *) 32'd0;
  assign _021_ = activity_timer[11:8] - (* src = "../../activity_counter.sv:85.42-85.66" *) 4'h1;
  assign _022_ = ! (* src = "../../activity_counter.sv:74.21-74.34" *) periph_en[3];
  assign _023_ = { 28'h0000000, activity_timer[15:12] } > (* src = "../../activity_counter.sv:83.30-83.51" *) 32'd0;
  assign _031_ = idle_counter[15:0] + (* src = "../../activity_counter.sv:55.40-55.62" *) 16'h0001;
  assign _025_ = activity_timer[15:12] - (* src = "../../activity_counter.sv:85.42-85.66" *) 4'h1;
  assign _026_ = { 28'h0000000, activity_timer[3:0] } > (* src = "../../activity_counter.sv:98.35-98.56" *) 32'd0;
  assign _027_ = _026_ && (* src = "../../activity_counter.sv:98.34-98.73" *) periph_en[0];
  assign _028_ = { 28'h0000000, activity_timer[7:4] } > (* src = "../../activity_counter.sv:98.35-98.56" *) 32'd0;
  assign _029_ = _028_ && (* src = "../../activity_counter.sv:98.34-98.73" *) periph_en[1];
  assign _030_ = { 28'h0000000, activity_timer[11:8] } > (* src = "../../activity_counter.sv:98.35-98.56" *) 32'd0;
  assign _032_ = _030_ && (* src = "../../activity_counter.sv:98.34-98.73" *) periph_en[2];
  assign _033_ = { 28'h0000000, activity_timer[15:12] } > (* src = "../../activity_counter.sv:98.35-98.56" *) 32'd0;
  assign _034_ = _033_ && (* src = "../../activity_counter.sv:98.34-98.73" *) periph_en[3];
  assign _035_ = ! (* src = "../../activity_counter.sv:45.21-45.34" *) periph_en[1];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[3:0] <= 4'h0;
    else activity_timer[3:0] <= _044_;
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[7:4] <= 4'h0;
    else activity_timer[7:4] <= _047_;
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[11:8] <= 4'h0;
    else activity_timer[11:8] <= _038_;
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[15:12] <= 4'h0;
    else activity_timer[15:12] <= _041_;
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[15:0] <= 16'h0000;
    else idle_counter[15:0] <= _050_;
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[31:16] <= 16'h0000;
    else idle_counter[31:16] <= _053_;
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[47:32] <= 16'h0000;
    else idle_counter[47:32] <= _056_;
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[63:48] <= 16'h0000;
    else idle_counter[63:48] <= _059_;
  assign _061_ = _062_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:55.21-55.63|../../activity_counter.sv:53.26-60.20" *) _004_ : 16'hffff;
  assign _063_ = _064_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:51.21-51.43|../../activity_counter.sv:49.26-60.20" *) 16'hxxxx : _061_;
  assign _065_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _063_ : 16'hxxxx;
  assign _067_ = _068_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:51.21-51.43|../../activity_counter.sv:49.26-60.20" *) 16'h0000 : _054_;
  assign _069_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _067_ : 16'hxxxx;
  assign _071_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _055_ : 16'h0000;
  assign _079_ = _085_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:81.21-81.62|../../activity_counter.sv:78.26-90.20" *) 4'h9 : _039_;
  assign _073_ = _074_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:55.21-55.63|../../activity_counter.sv:53.26-60.20" *) _001_ : 16'hffff;
  assign _075_ = _076_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:51.21-51.43|../../activity_counter.sv:49.26-60.20" *) 16'hxxxx : _073_;
  assign _077_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _075_ : 16'hxxxx;
  assign _080_ = _081_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:51.21-51.43|../../activity_counter.sv:49.26-60.20" *) 16'h0000 : _051_;
  assign _082_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _080_ : 16'hxxxx;
  assign _084_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _052_ : 16'h0000;
  assign _087_ = _088_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:55.21-55.63|../../activity_counter.sv:53.26-60.20" *) _031_ : 16'hffff;
  assign _089_ = _090_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:51.21-51.43|../../activity_counter.sv:49.26-60.20" *) 16'hxxxx : _087_;
  assign _091_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _089_ : 16'hxxxx;
  assign _098_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _079_ : 4'hx;
  assign _093_ = _094_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:51.21-51.43|../../activity_counter.sv:49.26-60.20" *) 16'h0000 : _048_;
  assign _095_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _093_ : 16'hxxxx;
  assign _097_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _049_ : 16'h0000;
  assign _101_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _040_ : 4'h0;
  assign _109_ = _115_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:85.21-85.67|../../activity_counter.sv:83.26-90.20" *) _025_ : 4'h0;
  assign _103_ = _104_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:85.21-85.67|../../activity_counter.sv:83.26-90.20" *) _021_ : 4'h0;
  assign _105_ = _106_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:81.21-81.62|../../activity_counter.sv:78.26-90.20" *) 4'hx : _103_;
  assign _107_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _105_ : 4'hx;
  assign _110_ = _111_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:81.21-81.62|../../activity_counter.sv:78.26-90.20" *) 4'h9 : _036_;
  assign _112_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _110_ : 4'hx;
  assign _114_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _037_ : 4'h0;
  assign _117_ = _118_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:85.21-85.67|../../activity_counter.sv:83.26-90.20" *) _017_ : 4'h0;
  assign _119_ = _120_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:81.21-81.62|../../activity_counter.sv:78.26-90.20" *) 4'hx : _117_;
  assign _121_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _119_ : 4'hx;
  assign _128_ = _136_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:81.21-81.62|../../activity_counter.sv:78.26-90.20" *) 4'hx : _109_;
  assign _123_ = _124_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:81.21-81.62|../../activity_counter.sv:78.26-90.20" *) 4'h9 : _045_;
  assign _125_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _123_ : 4'hx;
  assign _127_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _046_ : 4'h0;
  assign _130_ = _131_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:85.21-85.67|../../activity_counter.sv:83.26-90.20" *) _014_ : 4'h0;
  assign _132_ = _133_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:81.21-81.62|../../activity_counter.sv:78.26-90.20" *) 4'hx : _130_;
  assign _134_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _132_ : 4'hx;
  assign _137_ = _138_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:81.21-81.62|../../activity_counter.sv:78.26-90.20" *) 4'h9 : _042_;
  assign _139_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _137_ : 4'hx;
  assign _141_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _043_ : 4'h0;
  assign _149_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:76.21-76.45|../../activity_counter.sv:74.17-90.20" *) _128_ : 4'hx;
  assign _143_ = _144_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:55.21-55.63|../../activity_counter.sv:53.26-60.20" *) _008_ : 16'hffff;
  assign _145_ = _146_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:51.21-51.43|../../activity_counter.sv:49.26-60.20" *) 16'hxxxx : _143_;
  assign _147_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _145_ : 16'hxxxx;
  assign _150_ = _151_ ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:51.21-51.43|../../activity_counter.sv:49.26-60.20" *) 16'h0000 : _057_;
  assign _152_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _150_ : 16'hxxxx;
  assign _154_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../activity_counter.sv:47.21-47.43|../../activity_counter.sv:45.17-60.20" *) _058_ : 16'h0000;
  assign recent_activity = { _034_, _032_, _029_, _027_ };
  assign idle_count = idle_counter;
  assign _115_ = _023_;
  assign _136_ = activity_pulse[3];
  assign _155_ = _022_;
  assign _039_ = _149_;
  assign _085_ = activity_pulse[3];
  assign _100_ = _022_;
  assign _040_ = _098_;
  assign _102_ = _022_;
  assign _041_ = _101_;
  assign _104_ = _020_;
  assign _106_ = activity_pulse[2];
  assign _108_ = _019_;
  assign _036_ = _107_;
  assign _111_ = activity_pulse[2];
  assign _113_ = _019_;
  assign _037_ = _112_;
  assign _116_ = _019_;
  assign _038_ = _114_;
  assign _118_ = _016_;
  assign _120_ = activity_pulse[1];
  assign _122_ = _015_;
  assign _045_ = _121_;
  assign _124_ = activity_pulse[1];
  assign _126_ = _015_;
  assign _046_ = _125_;
  assign _129_ = _015_;
  assign _047_ = _127_;
  assign _131_ = _013_;
  assign _133_ = activity_pulse[0];
  assign _135_ = _012_;
  assign _042_ = _134_;
  assign _138_ = activity_pulse[0];
  assign _140_ = _012_;
  assign _043_ = _139_;
  assign _142_ = _012_;
  assign _044_ = _141_;
  assign _144_ = _007_;
  assign _146_ = activity_pulse[3];
  assign _148_ = _006_;
  assign _057_ = _147_;
  assign _151_ = activity_pulse[3];
  assign _153_ = _006_;
  assign _058_ = _152_;
  assign _060_ = _006_;
  assign _059_ = _154_;
  assign _062_ = _003_;
  assign _064_ = activity_pulse[2];
  assign _066_ = _002_;
  assign _054_ = _065_;
  assign _068_ = activity_pulse[2];
  assign _070_ = _002_;
  assign _055_ = _069_;
  assign _072_ = _002_;
  assign _056_ = _071_;
  assign _074_ = _000_;
  assign _076_ = activity_pulse[1];
  assign _078_ = _035_;
  assign _051_ = _077_;
  assign _081_ = activity_pulse[1];
  assign _083_ = _035_;
  assign _052_ = _082_;
  assign _086_ = _035_;
  assign _053_ = _084_;
  assign _088_ = _024_;
  assign _090_ = activity_pulse[0];
  assign _092_ = _018_;
  assign _048_ = _091_;
  assign _094_ = activity_pulse[0];
  assign _096_ = _018_;
  assign _049_ = _095_;
  assign _099_ = _018_;
  assign _050_ = _097_;
  assign _011_ = rst_n;
  assign _010_ = rst_n;
endmodule
