/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../../activity_counter.sv:8.8" *)
module activity_counter(clk, rst_n, activity_pulse, periph_en, idle_count, recent_activity);
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  (* src = "/app/eda.work/c49f66c9-9970-44e5-8c47-3d1251d01b11.edacmd/eda.work/activity_counter.synth/slang/activity_counter.v:33.8-33.13" *)
  wire _027_;
  (* src = "/app/eda.work/c49f66c9-9970-44e5-8c47-3d1251d01b11.edacmd/eda.work/activity_counter.synth/slang/activity_counter.v:35.8-35.13" *)
  wire _029_;
  (* src = "/app/eda.work/c49f66c9-9970-44e5-8c47-3d1251d01b11.edacmd/eda.work/activity_counter.synth/slang/activity_counter.v:38.8-38.13" *)
  wire _032_;
  (* src = "/app/eda.work/c49f66c9-9970-44e5-8c47-3d1251d01b11.edacmd/eda.work/activity_counter.synth/slang/activity_counter.v:40.8-40.13" *)
  wire _034_;
  (* src = "../../activity_counter.sv:74.17-90.20" *)
  wire [3:0] _038_;
  (* src = "../../activity_counter.sv:74.17-90.20" *)
  wire [3:0] _041_;
  (* src = "../../activity_counter.sv:74.17-90.20" *)
  wire [3:0] _044_;
  (* src = "../../activity_counter.sv:74.17-90.20" *)
  wire [3:0] _047_;
  (* src = "../../activity_counter.sv:45.17-60.20" *)
  wire [15:0] _050_;
  (* src = "../../activity_counter.sv:45.17-60.20" *)
  wire [15:0] _053_;
  (* src = "../../activity_counter.sv:45.17-60.20" *)
  wire [15:0] _056_;
  (* src = "../../activity_counter.sv:45.17-60.20" *)
  wire [15:0] _059_;
  (* src = "../../activity_counter.sv:18.37" *)
  input [3:0] activity_pulse;
  wire [3:0] activity_pulse;
  (* src = "../../activity_counter.sv:32.46" *)
  reg [15:0] activity_timer;
  (* src = "../../activity_counter.sv:14.37" *)
  input clk;
  wire clk;
  (* src = "../../activity_counter.sv:24.37" *)
  output [63:0] idle_count;
  wire [63:0] idle_count;
  (* src = "../../activity_counter.sv:31.29" *)
  reg [63:0] idle_counter;
  (* src = "../../activity_counter.sv:21.37" *)
  input [3:0] periph_en;
  wire [3:0] periph_en;
  (* src = "../../activity_counter.sv:25.37" *)
  output [3:0] recent_activity;
  wire [3:0] recent_activity;
  (* src = "../../activity_counter.sv:15.37" *)
  input rst_n;
  wire rst_n;
  assign _060_ = ~(activity_timer[1] | activity_timer[0]);
  assign _061_ = activity_timer[3] | activity_timer[2];
  assign _062_ = _060_ & ~(_061_);
  assign _027_ = periph_en[0] & ~(_062_);
  assign _063_ = ~(activity_timer[5] | activity_timer[4]);
  assign _064_ = activity_timer[7] | activity_timer[6];
  assign _065_ = _063_ & ~(_064_);
  assign _029_ = periph_en[1] & ~(_065_);
  assign _066_ = ~(activity_timer[8] | activity_timer[9]);
  assign _067_ = activity_timer[11] | activity_timer[10];
  assign _068_ = _066_ & ~(_067_);
  assign _032_ = periph_en[2] & ~(_068_);
  assign _069_ = ~(activity_timer[13] | activity_timer[12]);
  assign _070_ = activity_timer[14] | activity_timer[15];
  assign _071_ = _069_ & ~(_070_);
  assign _034_ = periph_en[3] & ~(_071_);
  assign _072_ = idle_counter[47] & idle_counter[46];
  assign _073_ = ~(idle_counter[45] & idle_counter[44]);
  assign _074_ = _072_ & ~(_073_);
  assign _075_ = ~(idle_counter[43] & idle_counter[42]);
  assign _076_ = ~(idle_counter[40] & idle_counter[41]);
  assign _077_ = _076_ | _075_;
  assign _078_ = _074_ & ~(_077_);
  assign _079_ = ~(idle_counter[38] & idle_counter[39]);
  assign _080_ = ~(idle_counter[37] & idle_counter[36]);
  assign _081_ = _080_ | _079_;
  assign _082_ = idle_counter[34] & idle_counter[35];
  assign _083_ = ~(idle_counter[33] & idle_counter[32]);
  assign _084_ = _083_ | ~(_082_);
  assign _085_ = _084_ | _081_;
  assign _086_ = _085_ | ~(_078_);
  assign _087_ = _086_ & idle_counter[32];
  assign _088_ = _087_ | activity_pulse[2];
  assign _056_[0] = periph_en[2] & ~(_088_);
  assign _089_ = idle_counter[33] ^ idle_counter[32];
  assign _090_ = _086_ & ~(_089_);
  assign _091_ = _090_ | activity_pulse[2];
  assign _056_[1] = periph_en[2] & ~(_091_);
  assign _092_ = ~(_083_ ^ idle_counter[34]);
  assign _093_ = _086_ & ~(_092_);
  assign _094_ = _093_ | activity_pulse[2];
  assign _056_[2] = periph_en[2] & ~(_094_);
  assign _095_ = idle_counter[34] & ~(_083_);
  assign _096_ = _095_ ^ idle_counter[35];
  assign _097_ = _086_ & ~(_096_);
  assign _098_ = _097_ | activity_pulse[2];
  assign _056_[3] = periph_en[2] & ~(_098_);
  assign _099_ = ~(_084_ ^ idle_counter[36]);
  assign _100_ = _086_ & ~(_099_);
  assign _101_ = _100_ | activity_pulse[2];
  assign _056_[4] = periph_en[2] & ~(_101_);
  assign _102_ = idle_counter[36] & ~(_084_);
  assign _103_ = _102_ ^ idle_counter[37];
  assign _104_ = _086_ & ~(_103_);
  assign _105_ = _104_ | activity_pulse[2];
  assign _056_[5] = periph_en[2] & ~(_105_);
  assign _106_ = _084_ | _080_;
  assign _107_ = ~(_106_ ^ idle_counter[38]);
  assign _108_ = _086_ & ~(_107_);
  assign _109_ = _108_ | activity_pulse[2];
  assign _056_[6] = periph_en[2] & ~(_109_);
  assign _110_ = idle_counter[38] & ~(_106_);
  assign _111_ = _110_ ^ idle_counter[39];
  assign _112_ = _086_ & ~(_111_);
  assign _113_ = _112_ | activity_pulse[2];
  assign _056_[7] = periph_en[2] & ~(_113_);
  assign _114_ = ~(_085_ ^ idle_counter[40]);
  assign _115_ = _086_ & ~(_114_);
  assign _116_ = _115_ | activity_pulse[2];
  assign _056_[8] = periph_en[2] & ~(_116_);
  assign _117_ = idle_counter[40] & ~(_085_);
  assign _118_ = _117_ ^ idle_counter[41];
  assign _119_ = _086_ & ~(_118_);
  assign _120_ = _119_ | activity_pulse[2];
  assign _056_[9] = periph_en[2] & ~(_120_);
  assign _121_ = _085_ | _076_;
  assign _122_ = ~(_121_ ^ idle_counter[42]);
  assign _123_ = _086_ & ~(_122_);
  assign _124_ = _123_ | activity_pulse[2];
  assign _056_[10] = periph_en[2] & ~(_124_);
  assign _125_ = idle_counter[42] & ~(_121_);
  assign _126_ = _125_ ^ idle_counter[43];
  assign _127_ = _086_ & ~(_126_);
  assign _128_ = _127_ | activity_pulse[2];
  assign _056_[11] = periph_en[2] & ~(_128_);
  assign _129_ = _085_ | _077_;
  assign _130_ = ~(_129_ ^ idle_counter[44]);
  assign _131_ = _086_ & ~(_130_);
  assign _132_ = _131_ | activity_pulse[2];
  assign _056_[12] = periph_en[2] & ~(_132_);
  assign _133_ = idle_counter[44] & ~(_129_);
  assign _134_ = _133_ ^ idle_counter[45];
  assign _135_ = _086_ & ~(_134_);
  assign _136_ = _135_ | activity_pulse[2];
  assign _056_[13] = periph_en[2] & ~(_136_);
  assign _137_ = _129_ | _073_;
  assign _138_ = ~(_137_ ^ idle_counter[46]);
  assign _139_ = _086_ & ~(_138_);
  assign _140_ = _139_ | activity_pulse[2];
  assign _056_[14] = periph_en[2] & ~(_140_);
  assign _141_ = idle_counter[46] & ~(_137_);
  assign _142_ = _141_ ^ idle_counter[47];
  assign _143_ = _086_ & ~(_142_);
  assign _144_ = _143_ | activity_pulse[2];
  assign _056_[15] = periph_en[2] & ~(_144_);
  assign _145_ = idle_counter[30] & idle_counter[31];
  assign _146_ = ~(idle_counter[28] & idle_counter[29]);
  assign _147_ = _145_ & ~(_146_);
  assign _148_ = ~(idle_counter[27] & idle_counter[26]);
  assign _149_ = ~(idle_counter[25] & idle_counter[24]);
  assign _150_ = _149_ | _148_;
  assign _151_ = _147_ & ~(_150_);
  assign _152_ = ~(idle_counter[23] & idle_counter[22]);
  assign _153_ = ~(idle_counter[20] & idle_counter[21]);
  assign _154_ = _153_ | _152_;
  assign _155_ = idle_counter[18] & idle_counter[19];
  assign _156_ = ~(idle_counter[17] & idle_counter[16]);
  assign _157_ = _156_ | ~(_155_);
  assign _158_ = _157_ | _154_;
  assign _159_ = _158_ | ~(_151_);
  assign _160_ = _159_ & idle_counter[16];
  assign _161_ = _160_ | activity_pulse[1];
  assign _053_[0] = periph_en[1] & ~(_161_);
  assign _162_ = idle_counter[17] ^ idle_counter[16];
  assign _163_ = _159_ & ~(_162_);
  assign _164_ = _163_ | activity_pulse[1];
  assign _053_[1] = periph_en[1] & ~(_164_);
  assign _165_ = ~(_156_ ^ idle_counter[18]);
  assign _166_ = _159_ & ~(_165_);
  assign _167_ = _166_ | activity_pulse[1];
  assign _053_[2] = periph_en[1] & ~(_167_);
  assign _168_ = idle_counter[18] & ~(_156_);
  assign _169_ = _168_ ^ idle_counter[19];
  assign _170_ = _159_ & ~(_169_);
  assign _171_ = _170_ | activity_pulse[1];
  assign _053_[3] = periph_en[1] & ~(_171_);
  assign _172_ = ~(_157_ ^ idle_counter[20]);
  assign _173_ = _159_ & ~(_172_);
  assign _174_ = _173_ | activity_pulse[1];
  assign _053_[4] = periph_en[1] & ~(_174_);
  assign _175_ = idle_counter[20] & ~(_157_);
  assign _176_ = _175_ ^ idle_counter[21];
  assign _177_ = _159_ & ~(_176_);
  assign _178_ = _177_ | activity_pulse[1];
  assign _053_[5] = periph_en[1] & ~(_178_);
  assign _179_ = _157_ | _153_;
  assign _180_ = ~(_179_ ^ idle_counter[22]);
  assign _181_ = _159_ & ~(_180_);
  assign _182_ = _181_ | activity_pulse[1];
  assign _053_[6] = periph_en[1] & ~(_182_);
  assign _183_ = idle_counter[22] & ~(_179_);
  assign _184_ = _183_ ^ idle_counter[23];
  assign _185_ = _159_ & ~(_184_);
  assign _186_ = _185_ | activity_pulse[1];
  assign _053_[7] = periph_en[1] & ~(_186_);
  assign _187_ = ~(_158_ ^ idle_counter[24]);
  assign _188_ = _159_ & ~(_187_);
  assign _189_ = _188_ | activity_pulse[1];
  assign _053_[8] = periph_en[1] & ~(_189_);
  assign _190_ = idle_counter[24] & ~(_158_);
  assign _191_ = _190_ ^ idle_counter[25];
  assign _192_ = _159_ & ~(_191_);
  assign _193_ = _192_ | activity_pulse[1];
  assign _053_[9] = periph_en[1] & ~(_193_);
  assign _194_ = _158_ | _149_;
  assign _195_ = ~(_194_ ^ idle_counter[26]);
  assign _196_ = _159_ & ~(_195_);
  assign _197_ = _196_ | activity_pulse[1];
  assign _053_[10] = periph_en[1] & ~(_197_);
  assign _198_ = idle_counter[26] & ~(_194_);
  assign _199_ = _198_ ^ idle_counter[27];
  assign _200_ = _159_ & ~(_199_);
  assign _201_ = _200_ | activity_pulse[1];
  assign _053_[11] = periph_en[1] & ~(_201_);
  assign _202_ = _158_ | _150_;
  assign _203_ = ~(_202_ ^ idle_counter[28]);
  assign _204_ = _159_ & ~(_203_);
  assign _205_ = _204_ | activity_pulse[1];
  assign _053_[12] = periph_en[1] & ~(_205_);
  assign _206_ = idle_counter[28] & ~(_202_);
  assign _207_ = _206_ ^ idle_counter[29];
  assign _208_ = _159_ & ~(_207_);
  assign _209_ = _208_ | activity_pulse[1];
  assign _053_[13] = periph_en[1] & ~(_209_);
  assign _210_ = _202_ | _146_;
  assign _211_ = ~(_210_ ^ idle_counter[30]);
  assign _212_ = _159_ & ~(_211_);
  assign _213_ = _212_ | activity_pulse[1];
  assign _053_[14] = periph_en[1] & ~(_213_);
  assign _214_ = idle_counter[30] & ~(_210_);
  assign _215_ = _214_ ^ idle_counter[31];
  assign _216_ = _159_ & ~(_215_);
  assign _217_ = _216_ | activity_pulse[1];
  assign _053_[15] = periph_en[1] & ~(_217_);
  assign _218_ = idle_counter[14] & idle_counter[15];
  assign _219_ = ~(idle_counter[13] & idle_counter[12]);
  assign _220_ = _218_ & ~(_219_);
  assign _221_ = ~(idle_counter[11] & idle_counter[10]);
  assign _222_ = ~(idle_counter[9] & idle_counter[8]);
  assign _223_ = _222_ | _221_;
  assign _224_ = _220_ & ~(_223_);
  assign _225_ = ~(idle_counter[6] & idle_counter[7]);
  assign _226_ = ~(idle_counter[4] & idle_counter[5]);
  assign _227_ = _226_ | _225_;
  assign _228_ = idle_counter[2] & idle_counter[3];
  assign _229_ = ~(idle_counter[1] & idle_counter[0]);
  assign _230_ = _229_ | ~(_228_);
  assign _231_ = _230_ | _227_;
  assign _232_ = _231_ | ~(_224_);
  assign _233_ = _232_ & idle_counter[0];
  assign _234_ = _233_ | activity_pulse[0];
  assign _050_[0] = periph_en[0] & ~(_234_);
  assign _235_ = idle_counter[1] ^ idle_counter[0];
  assign _236_ = _232_ & ~(_235_);
  assign _237_ = _236_ | activity_pulse[0];
  assign _050_[1] = periph_en[0] & ~(_237_);
  assign _238_ = ~(_229_ ^ idle_counter[2]);
  assign _239_ = _232_ & ~(_238_);
  assign _240_ = _239_ | activity_pulse[0];
  assign _050_[2] = periph_en[0] & ~(_240_);
  assign _241_ = idle_counter[2] & ~(_229_);
  assign _242_ = _241_ ^ idle_counter[3];
  assign _243_ = _232_ & ~(_242_);
  assign _244_ = _243_ | activity_pulse[0];
  assign _050_[3] = periph_en[0] & ~(_244_);
  assign _245_ = ~(_230_ ^ idle_counter[4]);
  assign _246_ = _232_ & ~(_245_);
  assign _247_ = _246_ | activity_pulse[0];
  assign _050_[4] = periph_en[0] & ~(_247_);
  assign _248_ = idle_counter[4] & ~(_230_);
  assign _249_ = _248_ ^ idle_counter[5];
  assign _250_ = _232_ & ~(_249_);
  assign _251_ = _250_ | activity_pulse[0];
  assign _050_[5] = periph_en[0] & ~(_251_);
  assign _252_ = _230_ | _226_;
  assign _253_ = ~(_252_ ^ idle_counter[6]);
  assign _254_ = _232_ & ~(_253_);
  assign _255_ = _254_ | activity_pulse[0];
  assign _050_[6] = periph_en[0] & ~(_255_);
  assign _256_ = idle_counter[6] & ~(_252_);
  assign _257_ = _256_ ^ idle_counter[7];
  assign _258_ = _232_ & ~(_257_);
  assign _259_ = _258_ | activity_pulse[0];
  assign _050_[7] = periph_en[0] & ~(_259_);
  assign _260_ = ~(_231_ ^ idle_counter[8]);
  assign _261_ = _232_ & ~(_260_);
  assign _262_ = _261_ | activity_pulse[0];
  assign _050_[8] = periph_en[0] & ~(_262_);
  assign _263_ = idle_counter[8] & ~(_231_);
  assign _264_ = _263_ ^ idle_counter[9];
  assign _265_ = _232_ & ~(_264_);
  assign _266_ = _265_ | activity_pulse[0];
  assign _050_[9] = periph_en[0] & ~(_266_);
  assign _267_ = _231_ | _222_;
  assign _268_ = ~(_267_ ^ idle_counter[10]);
  assign _269_ = _232_ & ~(_268_);
  assign _270_ = _269_ | activity_pulse[0];
  assign _050_[10] = periph_en[0] & ~(_270_);
  assign _271_ = idle_counter[10] & ~(_267_);
  assign _272_ = _271_ ^ idle_counter[11];
  assign _273_ = _232_ & ~(_272_);
  assign _274_ = _273_ | activity_pulse[0];
  assign _050_[11] = periph_en[0] & ~(_274_);
  assign _275_ = _231_ | _223_;
  assign _276_ = ~(_275_ ^ idle_counter[12]);
  assign _277_ = _232_ & ~(_276_);
  assign _278_ = _277_ | activity_pulse[0];
  assign _050_[12] = periph_en[0] & ~(_278_);
  assign _279_ = idle_counter[12] & ~(_275_);
  assign _280_ = _279_ ^ idle_counter[13];
  assign _281_ = _232_ & ~(_280_);
  assign _282_ = _281_ | activity_pulse[0];
  assign _050_[13] = periph_en[0] & ~(_282_);
  assign _283_ = _275_ | _219_;
  assign _284_ = ~(_283_ ^ idle_counter[14]);
  assign _285_ = _232_ & ~(_284_);
  assign _286_ = _285_ | activity_pulse[0];
  assign _050_[14] = periph_en[0] & ~(_286_);
  assign _287_ = idle_counter[14] & ~(_283_);
  assign _288_ = _287_ ^ idle_counter[15];
  assign _289_ = _232_ & ~(_288_);
  assign _290_ = _289_ | activity_pulse[0];
  assign _050_[15] = periph_en[0] & ~(_290_);
  assign _291_ = ~activity_pulse[3];
  assign _292_ = ~(_071_ | activity_timer[12]);
  assign _293_ = _291_ & ~(_292_);
  assign _041_[0] = periph_en[3] & ~(_293_);
  assign _294_ = activity_timer[13] ^ activity_timer[12];
  assign _295_ = _294_ | _071_;
  assign _296_ = _295_ | activity_pulse[3];
  assign _041_[1] = periph_en[3] & ~(_296_);
  assign _297_ = activity_timer[13] | activity_timer[12];
  assign _298_ = _297_ ^ activity_timer[14];
  assign _299_ = _298_ | _071_;
  assign _300_ = _299_ | activity_pulse[3];
  assign _041_[2] = periph_en[3] & ~(_300_);
  assign _301_ = ~(_297_ | activity_timer[14]);
  assign _302_ = _301_ ^ activity_timer[15];
  assign _303_ = _302_ & ~(_071_);
  assign _304_ = _291_ & ~(_303_);
  assign _041_[3] = periph_en[3] & ~(_304_);
  assign _305_ = ~activity_pulse[2];
  assign _306_ = ~(_068_ | activity_timer[8]);
  assign _307_ = _305_ & ~(_306_);
  assign _038_[0] = periph_en[2] & ~(_307_);
  assign _308_ = activity_timer[8] ^ activity_timer[9];
  assign _309_ = _308_ | _068_;
  assign _310_ = _309_ | activity_pulse[2];
  assign _038_[1] = periph_en[2] & ~(_310_);
  assign _311_ = activity_timer[8] | activity_timer[9];
  assign _312_ = _311_ ^ activity_timer[10];
  assign _313_ = _312_ | _068_;
  assign _314_ = _313_ | activity_pulse[2];
  assign _038_[2] = periph_en[2] & ~(_314_);
  assign _315_ = ~(_311_ | activity_timer[10]);
  assign _316_ = _315_ ^ activity_timer[11];
  assign _317_ = _316_ & ~(_068_);
  assign _318_ = _305_ & ~(_317_);
  assign _038_[3] = periph_en[2] & ~(_318_);
  assign _319_ = ~activity_pulse[1];
  assign _320_ = ~(_065_ | activity_timer[4]);
  assign _321_ = _319_ & ~(_320_);
  assign _047_[0] = periph_en[1] & ~(_321_);
  assign _322_ = activity_timer[5] ^ activity_timer[4];
  assign _323_ = _322_ | _065_;
  assign _324_ = _323_ | activity_pulse[1];
  assign _047_[1] = periph_en[1] & ~(_324_);
  assign _325_ = activity_timer[5] | activity_timer[4];
  assign _326_ = _325_ ^ activity_timer[6];
  assign _327_ = _326_ | _065_;
  assign _328_ = _327_ | activity_pulse[1];
  assign _047_[2] = periph_en[1] & ~(_328_);
  assign _329_ = ~(_325_ | activity_timer[6]);
  assign _330_ = _329_ ^ activity_timer[7];
  assign _331_ = _330_ & ~(_065_);
  assign _332_ = _319_ & ~(_331_);
  assign _047_[3] = periph_en[1] & ~(_332_);
  assign _333_ = ~activity_pulse[0];
  assign _334_ = ~(_062_ | activity_timer[0]);
  assign _335_ = _333_ & ~(_334_);
  assign _044_[0] = periph_en[0] & ~(_335_);
  assign _336_ = activity_timer[1] ^ activity_timer[0];
  assign _337_ = _336_ | _062_;
  assign _338_ = _337_ | activity_pulse[0];
  assign _044_[1] = periph_en[0] & ~(_338_);
  assign _339_ = activity_timer[1] | activity_timer[0];
  assign _340_ = _339_ ^ activity_timer[2];
  assign _341_ = _340_ | _062_;
  assign _342_ = _341_ | activity_pulse[0];
  assign _044_[2] = periph_en[0] & ~(_342_);
  assign _343_ = ~(_339_ | activity_timer[2]);
  assign _344_ = _343_ ^ activity_timer[3];
  assign _345_ = _344_ & ~(_062_);
  assign _346_ = _333_ & ~(_345_);
  assign _044_[3] = periph_en[0] & ~(_346_);
  assign _347_ = idle_counter[62] & idle_counter[63];
  assign _348_ = ~(idle_counter[60] & idle_counter[61]);
  assign _349_ = _347_ & ~(_348_);
  assign _350_ = ~(idle_counter[59] & idle_counter[58]);
  assign _351_ = ~(idle_counter[57] & idle_counter[56]);
  assign _352_ = _351_ | _350_;
  assign _353_ = _349_ & ~(_352_);
  assign _354_ = ~(idle_counter[54] & idle_counter[55]);
  assign _355_ = ~(idle_counter[53] & idle_counter[52]);
  assign _356_ = _355_ | _354_;
  assign _357_ = idle_counter[51] & idle_counter[50];
  assign _358_ = ~(idle_counter[49] & idle_counter[48]);
  assign _359_ = _358_ | ~(_357_);
  assign _360_ = _359_ | _356_;
  assign _361_ = _360_ | ~(_353_);
  assign _362_ = _361_ & idle_counter[48];
  assign _363_ = _362_ | activity_pulse[3];
  assign _059_[0] = periph_en[3] & ~(_363_);
  assign _364_ = idle_counter[49] ^ idle_counter[48];
  assign _365_ = _361_ & ~(_364_);
  assign _366_ = _365_ | activity_pulse[3];
  assign _059_[1] = periph_en[3] & ~(_366_);
  assign _367_ = ~(_358_ ^ idle_counter[50]);
  assign _368_ = _361_ & ~(_367_);
  assign _369_ = _368_ | activity_pulse[3];
  assign _059_[2] = periph_en[3] & ~(_369_);
  assign _370_ = idle_counter[50] & ~(_358_);
  assign _371_ = _370_ ^ idle_counter[51];
  assign _372_ = _361_ & ~(_371_);
  assign _373_ = _372_ | activity_pulse[3];
  assign _059_[3] = periph_en[3] & ~(_373_);
  assign _374_ = ~(_359_ ^ idle_counter[52]);
  assign _375_ = _361_ & ~(_374_);
  assign _376_ = _375_ | activity_pulse[3];
  assign _059_[4] = periph_en[3] & ~(_376_);
  assign _377_ = idle_counter[52] & ~(_359_);
  assign _378_ = _377_ ^ idle_counter[53];
  assign _379_ = _361_ & ~(_378_);
  assign _380_ = _379_ | activity_pulse[3];
  assign _059_[5] = periph_en[3] & ~(_380_);
  assign _381_ = _359_ | _355_;
  assign _382_ = ~(_381_ ^ idle_counter[54]);
  assign _383_ = _361_ & ~(_382_);
  assign _384_ = _383_ | activity_pulse[3];
  assign _059_[6] = periph_en[3] & ~(_384_);
  assign _385_ = idle_counter[54] & ~(_381_);
  assign _386_ = _385_ ^ idle_counter[55];
  assign _387_ = _361_ & ~(_386_);
  assign _388_ = _387_ | activity_pulse[3];
  assign _059_[7] = periph_en[3] & ~(_388_);
  assign _389_ = ~(_360_ ^ idle_counter[56]);
  assign _390_ = _361_ & ~(_389_);
  assign _391_ = _390_ | activity_pulse[3];
  assign _059_[8] = periph_en[3] & ~(_391_);
  assign _392_ = idle_counter[56] & ~(_360_);
  assign _393_ = _392_ ^ idle_counter[57];
  assign _394_ = _361_ & ~(_393_);
  assign _395_ = _394_ | activity_pulse[3];
  assign _059_[9] = periph_en[3] & ~(_395_);
  assign _396_ = _360_ | _351_;
  assign _397_ = ~(_396_ ^ idle_counter[58]);
  assign _398_ = _361_ & ~(_397_);
  assign _399_ = _398_ | activity_pulse[3];
  assign _059_[10] = periph_en[3] & ~(_399_);
  assign _400_ = idle_counter[58] & ~(_396_);
  assign _401_ = _400_ ^ idle_counter[59];
  assign _402_ = _361_ & ~(_401_);
  assign _403_ = _402_ | activity_pulse[3];
  assign _059_[11] = periph_en[3] & ~(_403_);
  assign _404_ = _360_ | _352_;
  assign _405_ = ~(_404_ ^ idle_counter[60]);
  assign _406_ = _361_ & ~(_405_);
  assign _407_ = _406_ | activity_pulse[3];
  assign _059_[12] = periph_en[3] & ~(_407_);
  assign _408_ = idle_counter[60] & ~(_404_);
  assign _409_ = _408_ ^ idle_counter[61];
  assign _410_ = _361_ & ~(_409_);
  assign _411_ = _410_ | activity_pulse[3];
  assign _059_[13] = periph_en[3] & ~(_411_);
  assign _412_ = _404_ | _348_;
  assign _413_ = ~(_412_ ^ idle_counter[62]);
  assign _414_ = _361_ & ~(_413_);
  assign _415_ = _414_ | activity_pulse[3];
  assign _059_[14] = periph_en[3] & ~(_415_);
  assign _416_ = idle_counter[62] & ~(_412_);
  assign _417_ = _416_ ^ idle_counter[63];
  assign _418_ = _361_ & ~(_417_);
  assign _419_ = _418_ | activity_pulse[3];
  assign _059_[15] = periph_en[3] & ~(_419_);
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[48] <= 1'h0;
    else idle_counter[48] <= _059_[0];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[49] <= 1'h0;
    else idle_counter[49] <= _059_[1];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[50] <= 1'h0;
    else idle_counter[50] <= _059_[2];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[51] <= 1'h0;
    else idle_counter[51] <= _059_[3];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[52] <= 1'h0;
    else idle_counter[52] <= _059_[4];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[53] <= 1'h0;
    else idle_counter[53] <= _059_[5];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[54] <= 1'h0;
    else idle_counter[54] <= _059_[6];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[55] <= 1'h0;
    else idle_counter[55] <= _059_[7];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[56] <= 1'h0;
    else idle_counter[56] <= _059_[8];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[57] <= 1'h0;
    else idle_counter[57] <= _059_[9];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[58] <= 1'h0;
    else idle_counter[58] <= _059_[10];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[59] <= 1'h0;
    else idle_counter[59] <= _059_[11];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[60] <= 1'h0;
    else idle_counter[60] <= _059_[12];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[61] <= 1'h0;
    else idle_counter[61] <= _059_[13];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[62] <= 1'h0;
    else idle_counter[62] <= _059_[14];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[63] <= 1'h0;
    else idle_counter[63] <= _059_[15];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[32] <= 1'h0;
    else idle_counter[32] <= _056_[0];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[33] <= 1'h0;
    else idle_counter[33] <= _056_[1];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[34] <= 1'h0;
    else idle_counter[34] <= _056_[2];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[35] <= 1'h0;
    else idle_counter[35] <= _056_[3];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[36] <= 1'h0;
    else idle_counter[36] <= _056_[4];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[37] <= 1'h0;
    else idle_counter[37] <= _056_[5];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[38] <= 1'h0;
    else idle_counter[38] <= _056_[6];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[39] <= 1'h0;
    else idle_counter[39] <= _056_[7];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[40] <= 1'h0;
    else idle_counter[40] <= _056_[8];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[41] <= 1'h0;
    else idle_counter[41] <= _056_[9];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[42] <= 1'h0;
    else idle_counter[42] <= _056_[10];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[43] <= 1'h0;
    else idle_counter[43] <= _056_[11];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[44] <= 1'h0;
    else idle_counter[44] <= _056_[12];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[45] <= 1'h0;
    else idle_counter[45] <= _056_[13];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[46] <= 1'h0;
    else idle_counter[46] <= _056_[14];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[47] <= 1'h0;
    else idle_counter[47] <= _056_[15];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[16] <= 1'h0;
    else idle_counter[16] <= _053_[0];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[17] <= 1'h0;
    else idle_counter[17] <= _053_[1];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[18] <= 1'h0;
    else idle_counter[18] <= _053_[2];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[19] <= 1'h0;
    else idle_counter[19] <= _053_[3];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[20] <= 1'h0;
    else idle_counter[20] <= _053_[4];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[21] <= 1'h0;
    else idle_counter[21] <= _053_[5];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[22] <= 1'h0;
    else idle_counter[22] <= _053_[6];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[23] <= 1'h0;
    else idle_counter[23] <= _053_[7];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[24] <= 1'h0;
    else idle_counter[24] <= _053_[8];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[25] <= 1'h0;
    else idle_counter[25] <= _053_[9];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[26] <= 1'h0;
    else idle_counter[26] <= _053_[10];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[27] <= 1'h0;
    else idle_counter[27] <= _053_[11];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[28] <= 1'h0;
    else idle_counter[28] <= _053_[12];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[29] <= 1'h0;
    else idle_counter[29] <= _053_[13];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[30] <= 1'h0;
    else idle_counter[30] <= _053_[14];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[31] <= 1'h0;
    else idle_counter[31] <= _053_[15];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[0] <= 1'h0;
    else idle_counter[0] <= _050_[0];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[1] <= 1'h0;
    else idle_counter[1] <= _050_[1];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[2] <= 1'h0;
    else idle_counter[2] <= _050_[2];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[3] <= 1'h0;
    else idle_counter[3] <= _050_[3];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[4] <= 1'h0;
    else idle_counter[4] <= _050_[4];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[5] <= 1'h0;
    else idle_counter[5] <= _050_[5];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[6] <= 1'h0;
    else idle_counter[6] <= _050_[6];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[7] <= 1'h0;
    else idle_counter[7] <= _050_[7];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[8] <= 1'h0;
    else idle_counter[8] <= _050_[8];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[9] <= 1'h0;
    else idle_counter[9] <= _050_[9];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[10] <= 1'h0;
    else idle_counter[10] <= _050_[10];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[11] <= 1'h0;
    else idle_counter[11] <= _050_[11];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[12] <= 1'h0;
    else idle_counter[12] <= _050_[12];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[13] <= 1'h0;
    else idle_counter[13] <= _050_[13];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[14] <= 1'h0;
    else idle_counter[14] <= _050_[14];
  (* src = "../../activity_counter.sv:40.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) idle_counter[15] <= 1'h0;
    else idle_counter[15] <= _050_[15];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[12] <= 1'h0;
    else activity_timer[12] <= _041_[0];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[13] <= 1'h0;
    else activity_timer[13] <= _041_[1];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[14] <= 1'h0;
    else activity_timer[14] <= _041_[2];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[15] <= 1'h0;
    else activity_timer[15] <= _041_[3];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[8] <= 1'h0;
    else activity_timer[8] <= _038_[0];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[9] <= 1'h0;
    else activity_timer[9] <= _038_[1];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[10] <= 1'h0;
    else activity_timer[10] <= _038_[2];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[11] <= 1'h0;
    else activity_timer[11] <= _038_[3];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[4] <= 1'h0;
    else activity_timer[4] <= _047_[0];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[5] <= 1'h0;
    else activity_timer[5] <= _047_[1];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[6] <= 1'h0;
    else activity_timer[6] <= _047_[2];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[7] <= 1'h0;
    else activity_timer[7] <= _047_[3];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[0] <= 1'h0;
    else activity_timer[0] <= _044_[0];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[1] <= 1'h0;
    else activity_timer[1] <= _044_[1];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[2] <= 1'h0;
    else activity_timer[2] <= _044_[2];
  (* src = "../../activity_counter.sv:69.5" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) activity_timer[3] <= 1'h0;
    else activity_timer[3] <= _044_[3];
  assign idle_count = idle_counter;
  assign recent_activity = { _034_, _032_, _029_, _027_ };
endmodule
