/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../../power_fsm.sv:10.8" *)
module power_fsm(clk, rst_n, sleep_eligible, wake_evt, periph_en, state, clk_req);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  (* src = "../../power_fsm.sv:134.17-140.20" *)
  wire _028_;
  (* src = "../../power_fsm.sv:134.17-140.20" *)
  wire _029_;
  (* src = "../../power_fsm.sv:134.17-140.20" *)
  wire _030_;
  (* src = "../../power_fsm.sv:134.17-140.20" *)
  wire _031_;
  wire [1:0] _032_;
  wire _033_;
  wire [1:0] _034_;
  wire _035_;
  wire _036_;
  wire [1:0] _037_;
  wire _038_;
  wire [1:0] _039_;
  wire _040_;
  wire [1:0] _041_;
  wire _042_;
  wire [1:0] _043_;
  wire _044_;
  wire [1:0] _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire [1:0] _049_;
  wire _050_;
  wire [1:0] _051_;
  wire [1:0] _052_;
  wire _053_;
  wire [1:0] _054_;
  wire _055_;
  wire [1:0] _056_;
  wire _057_;
  wire _058_;
  wire [1:0] _059_;
  wire _060_;
  wire [1:0] _061_;
  wire _062_;
  wire [1:0] _063_;
  wire _064_;
  wire [1:0] _065_;
  wire _066_;
  wire [1:0] _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire [1:0] _071_;
  wire _072_;
  wire _073_;
  wire [1:0] _074_;
  wire _075_;
  wire [1:0] _076_;
  wire _077_;
  wire _078_;
  wire [1:0] _079_;
  wire _080_;
  wire [1:0] _081_;
  wire _082_;
  wire [1:0] _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire [1:0] _087_;
  wire _088_;
  wire [1:0] _089_;
  wire _090_;
  wire [1:0] _091_;
  wire [1:0] _092_;
  wire _093_;
  wire [1:0] _094_;
  wire _095_;
  wire [1:0] _096_;
  wire _097_;
  wire _098_;
  wire [1:0] _099_;
  wire _100_;
  wire [1:0] _101_;
  wire _102_;
  wire [1:0] _103_;
  wire _104_;
  wire [1:0] _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire [1:0] _109_;
  wire _110_;
  wire [1:0] _111_;
  wire _112_;
  wire _113_;
  wire [1:0] _114_;
  wire _115_;
  wire [1:0] _116_;
  wire _117_;
  wire [1:0] _118_;
  wire _119_;
  wire _120_;
  wire [1:0] _121_;
  wire _122_;
  wire [1:0] _123_;
  wire _124_;
  wire [1:0] _125_;
  wire _126_;
  wire [1:0] _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire [1:0] _131_;
  wire _132_;
  wire [1:0] _133_;
  wire _134_;
  wire [1:0] _135_;
  wire _136_;
  wire [1:0] _137_;
  wire _138_;
  wire [1:0] _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire [1:0] _143_;
  wire _144_;
  wire [1:0] _145_;
  wire [1:0] _146_;
  wire _147_;
  wire [1:0] _148_;
  wire _149_;
  wire [1:0] _150_;
  wire _151_;
  wire _152_;
  wire [1:0] _153_;
  wire _154_;
  wire [1:0] _155_;
  wire _156_;
  wire [1:0] _157_;
  wire _158_;
  wire [1:0] _159_;
  (* src = "../../power_fsm.sv:80.29-82.32" *)
  wire [1:0] _160_;
  (* src = "../../power_fsm.sv:88.29-94.32" *)
  wire [1:0] _161_;
  (* src = "../../power_fsm.sv:76.21-108.28" *)
  wire [1:0] _162_;
  (* src = "../../power_fsm.sv:70.22-109.20" *)
  wire [1:0] _163_;
  (* src = "../../power_fsm.sv:65.17-109.20" *)
  wire [1:0] _164_;
  (* src = "../../power_fsm.sv:80.29-82.32" *)
  wire [1:0] _165_;
  (* src = "../../power_fsm.sv:88.29-94.32" *)
  wire [1:0] _166_;
  (* src = "../../power_fsm.sv:76.21-108.28" *)
  wire [1:0] _167_;
  (* src = "../../power_fsm.sv:70.22-109.20" *)
  wire [1:0] _168_;
  (* src = "../../power_fsm.sv:65.17-109.20" *)
  wire [1:0] _169_;
  (* src = "../../power_fsm.sv:80.29-82.32" *)
  wire [1:0] _170_;
  (* src = "../../power_fsm.sv:88.29-94.32" *)
  wire [1:0] _171_;
  (* src = "../../power_fsm.sv:76.21-108.28" *)
  wire [1:0] _172_;
  (* src = "../../power_fsm.sv:70.22-109.20" *)
  wire [1:0] _173_;
  (* src = "../../power_fsm.sv:65.17-109.20" *)
  wire [1:0] _174_;
  (* src = "../../power_fsm.sv:80.29-82.32" *)
  wire [1:0] _175_;
  (* src = "../../power_fsm.sv:88.29-94.32" *)
  wire [1:0] _176_;
  (* src = "../../power_fsm.sv:76.21-108.28" *)
  wire [1:0] _177_;
  (* src = "../../power_fsm.sv:70.22-109.20" *)
  wire [1:0] _178_;
  (* src = "../../power_fsm.sv:65.17-109.20" *)
  wire [1:0] _179_;
  (* src = "../../power_fsm.sv:14.30" *)
  input clk;
  wire clk;
  (* src = "../../power_fsm.sv:24.31" *)
  output [3:0] clk_req;
  wire [3:0] clk_req;
  (* src = "../../power_fsm.sv:20.30" *)
  input [3:0] periph_en;
  wire [3:0] periph_en;
  (* src = "../../power_fsm.sv:15.30" *)
  input rst_n;
  wire rst_n;
  (* src = "../../power_fsm.sv:18.30" *)
  input [3:0] sleep_eligible;
  wire [3:0] sleep_eligible;
  (* src = "../../power_fsm.sv:23.31" *)
  output [7:0] state;
  reg [7:0] state;
  (* src = "../../power_fsm.sv:39.24" *)
  wire [7:0] state_next;
  (* src = "../../power_fsm.sv:19.30" *)
  input [3:0] wake_evt;
  wire [3:0] wake_evt;
  assign _005_ = ! (* src = "../../power_fsm.sv:65.21-65.34" *) periph_en[0];
  assign _000_ = ! (* src = "../../power_fsm.sv:134.21-134.34" *) periph_en[0];
  assign _001_ = ! (* src = "../../power_fsm.sv:139.35-139.53" *) state[1:0];
  assign _002_ = state[1:0] == (* src = "../../power_fsm.sv:139.59-139.75" *) 2'h1;
  assign _003_ = _001_ || (* src = "../../power_fsm.sv:139.34-139.76" *) _002_;
  assign _004_ = ! (* src = "../../power_fsm.sv:65.21-65.34" *) periph_en[1];
  assign _006_ = ! rst_n;
  assign _008_ = ! (* src = "../../power_fsm.sv:134.21-134.34" *) periph_en[1];
  assign _009_ = ! (* src = "../../power_fsm.sv:139.35-139.53" *) state[3:2];
  assign _010_ = state[3:2] == (* src = "../../power_fsm.sv:139.59-139.75" *) 2'h1;
  assign _011_ = _009_ || (* src = "../../power_fsm.sv:139.34-139.76" *) _010_;
  assign _012_ = ! (* src = "../../power_fsm.sv:65.21-65.34" *) periph_en[2];
  assign _013_ = ! rst_n;
  assign _015_ = ! (* src = "../../power_fsm.sv:134.21-134.34" *) periph_en[2];
  assign _016_ = ! (* src = "../../power_fsm.sv:139.35-139.53" *) state[5:4];
  assign _017_ = state[5:4] == (* src = "../../power_fsm.sv:139.59-139.75" *) 2'h1;
  assign _018_ = _016_ || (* src = "../../power_fsm.sv:139.34-139.76" *) _017_;
  assign _019_ = ! (* src = "../../power_fsm.sv:65.21-65.34" *) periph_en[3];
  assign _020_ = ! rst_n;
  assign _022_ = ! (* src = "../../power_fsm.sv:134.21-134.34" *) periph_en[3];
  assign _023_ = ! (* src = "../../power_fsm.sv:139.35-139.53" *) state[7:6];
  assign _024_ = state[7:6] == (* src = "../../power_fsm.sv:139.59-139.75" *) 2'h1;
  assign _025_ = _023_ || (* src = "../../power_fsm.sv:139.34-139.76" *) _024_;
  assign _026_ = ! rst_n;
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[1:0] <= 2'h0;
    else state[1:0] <= state_next[1:0];
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[3:2] <= 2'h0;
    else state[3:2] <= state_next[3:2];
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[5:4] <= 2'h0;
    else state[5:4] <= state_next[5:4];
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[7:6] <= 2'h0;
    else state[7:6] <= state_next[7:6];
  assign _032_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _157_ : 2'hx;
  assign _034_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _178_ : 2'h2;
  assign _036_ = state[5:4] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) 2'h1;
  assign _037_ = _038_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:89.33-89.55|../../power_fsm.sv:88.29-94.32" *) 2'h2 : 2'h0;
  assign _039_ = _040_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) _037_ : 2'hx;
  assign _040_ = state[3:2] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) 2'h1;
  assign _041_ = _042_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _039_;
  assign _043_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _041_ : 2'hx;
  assign _051_ = _058_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _159_;
  function [1:0] _217_;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../power_fsm.sv:100.29-100.51|../../power_fsm.sv:76.21-108.28" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _217_ = b[1:0];
      3'b?1?:
        _217_ = b[3:2];
      3'b1??:
        _217_ = b[5:4];
      default:
        _217_ = a;
    endcase
  endfunction
  assign _045_ = _217_(2'h0, { _165_, _166_, 2'h2 }, { _048_, _047_, _046_ });
  assign _046_ = state[3:2] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:100.29-100.51|../../power_fsm.sv:76.21-108.28" *) 2'h2;
  assign _047_ = state[3:2] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) 2'h1;
  assign _048_ = ! (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) state[3:2];
  assign _049_ = _050_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _045_;
  assign _052_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _049_ : 2'hx;
  assign _054_ = _055_ ? (* src = "../../power_fsm.sv:81.33-81.54|../../power_fsm.sv:80.29-82.32" *) 2'h1 : state[3:2];
  assign _056_ = _057_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) _054_ : 2'hx;
  assign _057_ = ! (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) state[3:2];
  assign _059_ = _060_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _056_;
  assign _061_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _059_ : 2'hx;
  assign _063_ = _064_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'h0 : _167_;
  assign _071_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _051_ : 2'hx;
  assign _065_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _063_ : 2'hx;
  assign _067_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _168_ : 2'h2;
  assign _069_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:136.21-136.39|../../power_fsm.sv:134.17-140.20" *) _003_ : 1'h0;
  assign _072_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:136.21-136.39|../../power_fsm.sv:134.17-140.20" *) _018_ : 1'h0;
  assign _074_ = _075_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:89.33-89.55|../../power_fsm.sv:88.29-94.32" *) 2'h2 : 2'h0;
  assign _076_ = _077_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) _074_ : 2'hx;
  assign _077_ = state[1:0] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) 2'h1;
  assign _079_ = _080_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _076_;
  assign _081_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _079_ : 2'hx;
  function [1:0] _239_;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../power_fsm.sv:100.29-100.51|../../power_fsm.sv:76.21-108.28" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _239_ = b[1:0];
      3'b?1?:
        _239_ = b[3:2];
      3'b1??:
        _239_ = b[5:4];
      default:
        _239_ = a;
    endcase
  endfunction
  assign _083_ = _239_(2'h0, { _160_, _161_, 2'h2 }, { _086_, _085_, _084_ });
  assign _084_ = state[1:0] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:100.29-100.51|../../power_fsm.sv:76.21-108.28" *) 2'h2;
  function [1:0] _241_;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../power_fsm.sv:100.29-100.51|../../power_fsm.sv:76.21-108.28" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _241_ = b[1:0];
      3'b?1?:
        _241_ = b[3:2];
      3'b1??:
        _241_ = b[5:4];
      default:
        _241_ = a;
    endcase
  endfunction
  assign _091_ = _241_(2'h0, { _170_, _171_, 2'h2 }, { _108_, _107_, _098_ });
  assign _085_ = state[1:0] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) 2'h1;
  assign _086_ = ! (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) state[1:0];
  assign _087_ = _088_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _083_;
  assign _089_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _087_ : 2'hx;
  assign _092_ = _093_ ? (* src = "../../power_fsm.sv:81.33-81.54|../../power_fsm.sv:80.29-82.32" *) 2'h1 : state[1:0];
  assign _094_ = _095_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) _092_ : 2'hx;
  assign _095_ = ! (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) state[1:0];
  assign _096_ = _097_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _094_;
  assign _098_ = state[5:4] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:100.29-100.51|../../power_fsm.sv:76.21-108.28" *) 2'h2;
  assign _113_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:136.21-136.39|../../power_fsm.sv:134.17-140.20" *) _025_ : 1'h0;
  assign _099_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _096_ : 2'hx;
  assign _101_ = _102_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'h0 : _162_;
  assign _103_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _101_ : 2'hx;
  assign _105_ = periph_en[0] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _163_ : 2'h2;
  assign _107_ = state[5:4] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) 2'h1;
  assign _108_ = ! (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) state[5:4];
  assign _109_ = _110_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _091_;
  assign _111_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _109_ : 2'hx;
  assign _114_ = _115_ ? (* src = "../../power_fsm.sv:81.33-81.54|../../power_fsm.sv:80.29-82.32" *) 2'h1 : state[5:4];
  assign _116_ = _117_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) _114_ : 2'hx;
  assign _117_ = ! (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) state[5:4];
  assign _118_ = _119_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _116_;
  assign _121_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _118_ : 2'hx;
  assign _123_ = _124_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'h0 : _172_;
  assign _125_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _123_ : 2'hx;
  assign _127_ = periph_en[2] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _173_ : 2'h2;
  assign _129_ = periph_en[1] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:136.21-136.39|../../power_fsm.sv:134.17-140.20" *) _011_ : 1'h0;
  assign _131_ = _132_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:89.33-89.55|../../power_fsm.sv:88.29-94.32" *) 2'h2 : 2'h0;
  assign _133_ = _134_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) _131_ : 2'hx;
  assign _134_ = state[7:6] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) 2'h1;
  assign _135_ = _136_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _133_;
  assign _137_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _135_ : 2'hx;
  assign _145_ = _152_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:89.33-89.55|../../power_fsm.sv:88.29-94.32" *) 2'h2 : 2'h0;
  function [1:0] _275_;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "../../power_fsm.sv:100.29-100.51|../../power_fsm.sv:76.21-108.28" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _275_ = b[1:0];
      3'b?1?:
        _275_ = b[3:2];
      3'b1??:
        _275_ = b[5:4];
      default:
        _275_ = a;
    endcase
  endfunction
  assign _139_ = _275_(2'h0, { _175_, _176_, 2'h2 }, { _142_, _141_, _140_ });
  assign _140_ = state[7:6] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:100.29-100.51|../../power_fsm.sv:76.21-108.28" *) 2'h2;
  assign _141_ = state[7:6] == (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) 2'h1;
  assign _142_ = ! (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) state[7:6];
  assign _143_ = _144_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _139_;
  assign _146_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _143_ : 2'hx;
  assign _148_ = _149_ ? (* src = "../../power_fsm.sv:81.33-81.54|../../power_fsm.sv:80.29-82.32" *) 2'h1 : state[7:6];
  assign _150_ = _151_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) _148_ : 2'hx;
  assign _151_ = ! (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:80.29-82.32|../../power_fsm.sv:76.21-108.28" *) state[7:6];
  assign _159_ = _036_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:88.29-94.32|../../power_fsm.sv:76.21-108.28" *) _145_ : 2'hx;
  assign _153_ = _154_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'hx : _150_;
  assign _155_ = periph_en[3] ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:66.21-66.43|../../power_fsm.sv:65.17-109.20" *) _153_ : 2'hx;
  assign _157_ = _158_ ? (* full_case = 32'd1 *) (* src = "../../power_fsm.sv:71.21-71.44|../../power_fsm.sv:70.22-109.20" *) 2'h0 : _177_;
  assign state_next[1:0] = _164_;
  assign clk_req[0] = _028_;
  assign state_next[3:2] = _169_;
  assign clk_req[1] = _029_;
  assign state_next[5:4] = _174_;
  assign clk_req[2] = _030_;
  assign state_next[7:6] = _179_;
  assign clk_req[3] = _031_;
  assign _120_ = _022_;
  assign _031_ = _113_;
  assign _152_ = sleep_eligible[2];
  assign _058_ = wake_evt[2];
  assign _078_ = _012_;
  assign _171_ = _071_;
  assign _110_ = wake_evt[2];
  assign _112_ = _012_;
  assign _172_ = _111_;
  assign _115_ = sleep_eligible[2];
  assign _119_ = wake_evt[2];
  assign _122_ = _012_;
  assign _170_ = _121_;
  assign _124_ = wake_evt[2];
  assign _126_ = _012_;
  assign _173_ = _125_;
  assign _128_ = _012_;
  assign _174_ = _127_;
  assign _130_ = _008_;
  assign _029_ = _129_;
  assign _132_ = sleep_eligible[3];
  assign _136_ = wake_evt[3];
  assign _138_ = _019_;
  assign _176_ = _137_;
  assign _144_ = wake_evt[3];
  assign _147_ = _019_;
  assign _177_ = _146_;
  assign _149_ = sleep_eligible[3];
  assign _154_ = wake_evt[3];
  assign _156_ = _019_;
  assign _175_ = _155_;
  assign _158_ = wake_evt[3];
  assign _033_ = _019_;
  assign _178_ = _032_;
  assign _035_ = _019_;
  assign _179_ = _034_;
  assign _038_ = sleep_eligible[1];
  assign _042_ = wake_evt[1];
  assign _044_ = _004_;
  assign _166_ = _043_;
  assign _050_ = wake_evt[1];
  assign _053_ = _004_;
  assign _167_ = _052_;
  assign _055_ = sleep_eligible[1];
  assign _060_ = wake_evt[1];
  assign _062_ = _004_;
  assign _165_ = _061_;
  assign _064_ = wake_evt[1];
  assign _066_ = _004_;
  assign _168_ = _065_;
  assign _068_ = _004_;
  assign _169_ = _067_;
  assign _070_ = _000_;
  assign _028_ = _069_;
  assign _073_ = _015_;
  assign _030_ = _072_;
  assign _075_ = sleep_eligible[0];
  assign _080_ = wake_evt[0];
  assign _082_ = _005_;
  assign _161_ = _081_;
  assign _088_ = wake_evt[0];
  assign _090_ = _005_;
  assign _162_ = _089_;
  assign _093_ = sleep_eligible[0];
  assign _097_ = wake_evt[0];
  assign _100_ = _005_;
  assign _160_ = _099_;
  assign _102_ = wake_evt[0];
  assign _104_ = _005_;
  assign _163_ = _103_;
  assign _106_ = _005_;
  assign _164_ = _105_;
  assign _027_ = rst_n;
  assign _007_ = rst_n;
  assign _014_ = rst_n;
  assign _021_ = rst_n;
endmodule
