/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "../../power_fsm.sv:10.8" *)
module power_fsm(clk, rst_n, sleep_eligible, wake_evt, periph_en, state, clk_req);
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  (* src = "../../power_fsm.sv:134.17-140.20" *)
  wire _028_;
  (* src = "../../power_fsm.sv:134.17-140.20" *)
  wire _029_;
  (* src = "../../power_fsm.sv:134.17-140.20" *)
  wire _030_;
  (* src = "../../power_fsm.sv:134.17-140.20" *)
  wire _031_;
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:44.14-44.19" *)
  wire [1:0] _034_;
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:77.14-77.19" *)
  wire [1:0] _067_;
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:115.14-115.19" *)
  wire [1:0] _105_;
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:137.14-137.19" *)
  wire [1:0] _127_;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:284.17-284.18" *)
  wire [5:0] \_217_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:300$5.b ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:285.17-285.18" *)
  wire [2:0] \_217_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:300$5.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:324.17-324.18" *)
  wire [5:0] \_239_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:340$6.b ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:325.17-325.18" *)
  wire [2:0] \_239_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:340$6.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:344.17-344.18" *)
  wire [5:0] \_241_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:360$7.b ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:345.17-345.18" *)
  wire [2:0] \_241_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:360$7.s ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:396.17-396.18" *)
  wire [5:0] \_275_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:412$8.b ;
  (* nosync = 32'd1 *)
  (* src = "/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:397.17-397.18" *)
  wire [2:0] \_275_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:412$8.s ;
  (* src = "../../power_fsm.sv:14.30" *)
  input clk;
  wire clk;
  (* src = "../../power_fsm.sv:24.31" *)
  output [3:0] clk_req;
  wire [3:0] clk_req;
  (* src = "../../power_fsm.sv:20.30" *)
  input [3:0] periph_en;
  wire [3:0] periph_en;
  (* src = "../../power_fsm.sv:15.30" *)
  input rst_n;
  wire rst_n;
  (* src = "../../power_fsm.sv:18.30" *)
  input [3:0] sleep_eligible;
  wire [3:0] sleep_eligible;
  (* src = "../../power_fsm.sv:23.31" *)
  output [7:0] state;
  reg [7:0] state;
  (* src = "../../power_fsm.sv:39.24" *)
  wire [7:0] state_next;
  (* src = "../../power_fsm.sv:19.30" *)
  input [3:0] wake_evt;
  wire [3:0] wake_evt;
  assign _132_ = ~periph_en[0];
  assign _133_ = state[1] | state[0];
  assign _134_ = _133_ | _132_;
  assign _135_ = wake_evt[0] | sleep_eligible[0];
  assign _128_ = _135_ | _134_;
  assign _136_ = ~periph_en[1];
  assign _137_ = state[3] | state[2];
  assign _138_ = _137_ | _136_;
  assign _139_ = wake_evt[1] | sleep_eligible[1];
  assign _129_ = _139_ | _138_;
  assign _140_ = ~periph_en[2];
  assign _141_ = state[4] | state[5];
  assign _142_ = _141_ | _140_;
  assign _143_ = wake_evt[2] | sleep_eligible[2];
  assign _130_ = _143_ | _142_;
  assign _144_ = ~periph_en[3];
  assign _145_ = state[6] | state[7];
  assign _146_ = _145_ | _144_;
  assign _147_ = wake_evt[3] | sleep_eligible[3];
  assign _131_ = _147_ | _146_;
  assign _148_ = _145_ | wake_evt[3];
  assign _034_[0] = periph_en[3] & ~(_148_);
  assign _149_ = state[7] | ~(state[6]);
  assign _150_ = _149_ | ~(sleep_eligible[3]);
  assign _151_ = state[7] ? state[6] : _150_;
  assign _152_ = ~(_151_ | wake_evt[3]);
  assign _034_[1] = _152_ | _144_;
  assign _153_ = _137_ | wake_evt[1];
  assign _067_[0] = periph_en[1] & ~(_153_);
  assign _154_ = state[3] | ~(state[2]);
  assign _155_ = _154_ | ~(sleep_eligible[1]);
  assign _156_ = state[3] ? state[2] : _155_;
  assign _157_ = ~(_156_ | wake_evt[1]);
  assign _067_[1] = _157_ | _136_;
  assign _158_ = _133_ | wake_evt[0];
  assign _105_[0] = periph_en[0] & ~(_158_);
  assign _159_ = state[1] | ~(state[0]);
  assign _160_ = _159_ | ~(sleep_eligible[0]);
  assign _161_ = state[1] ? state[0] : _160_;
  assign _162_ = ~(_161_ | wake_evt[0]);
  assign _105_[1] = _162_ | _132_;
  assign _163_ = _141_ | wake_evt[2];
  assign _127_[0] = periph_en[2] & ~(_163_);
  assign _164_ = state[5] | ~(state[4]);
  assign _165_ = _164_ | ~(sleep_eligible[2]);
  assign _166_ = state[5] ? state[4] : _165_;
  assign _167_ = ~(_166_ | wake_evt[2]);
  assign _127_[1] = _167_ | _140_;
  assign _168_ = _159_ & _133_;
  assign _028_ = periph_en[0] & ~(_168_);
  assign _169_ = _164_ & _141_;
  assign _030_ = periph_en[2] & ~(_169_);
  assign _170_ = _149_ & _145_;
  assign _031_ = periph_en[3] & ~(_170_);
  assign _171_ = _154_ & _137_;
  assign _029_ = periph_en[1] & ~(_171_);
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[0] <= 1'h0;
    else if (_128_) state[0] <= _105_[0];
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[1] <= 1'h0;
    else if (_128_) state[1] <= _105_[1];
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[6] <= 1'h0;
    else if (_131_) state[6] <= _034_[0];
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[7] <= 1'h0;
    else if (_131_) state[7] <= _034_[1];
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[4] <= 1'h0;
    else if (_130_) state[4] <= _127_[0];
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[5] <= 1'h0;
    else if (_130_) state[5] <= _127_[1];
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[2] <= 1'h0;
    else if (_129_) state[2] <= _067_[0];
  (* src = "../../power_fsm.sv:118.13" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[3] <= 1'h0;
    else if (_129_) state[3] <= _067_[1];
  assign \_217_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:300$5.b  = 6'hxx;
  assign \_217_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:300$5.s  = 3'hx;
  assign \_239_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:340$6.b  = 6'hxx;
  assign \_239_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:340$6.s  = 3'hx;
  assign \_241_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:360$7.b  = 6'hxx;
  assign \_241_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:360$7.s  = 3'hx;
  assign \_275_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:412$8.b  = 6'hxx;
  assign \_275_$func$/app/eda.work/a0d2aa74-dbbc-40f6-8a8c-fe25657ee01c.edacmd/eda.work/power_fsm.synth/slang/power_fsm.v:412$8.s  = 3'hx;
  assign clk_req = { _031_, _030_, _029_, _028_ };
  assign state_next = { _034_, _127_, _067_, _105_ };
endmodule
